### ISSUE TITLE
Location of public mailing list / IRC

### ISSUE THREAD

**Issue by ribalda** [RadeonOpenCompute/ROCm#103]
Is there anyway to communicate with the developers?

It is a great step forward the use of github. But it would be highly appreciated if the development is a bit more open.

**Comment by jpsamaroo** [comment]
@gstoner is there a reason why this issue was closed immediately after being opened? It's not clear whether or not a means of non-contribution-related communication is available for anyone interested in discussing ROCm.

Having a mailing list and/or IRC channel available for discussion and support pertaining to ROCm usage would help to stop people from opening issues on the various projects' issue trackers just to ask usage questions. Having a public communication channel is also beneficial to helping the project gain traction with regular users who might want to discuss topics or ask questions that aren't necessarily related to a single Github-hosted project. Without one, it just feels to an outsider like no one actually uses ROCm, since there's no visible community other than just developers and contributors.

I therefore request that we reopen this issue until some sort of communication mechanism (other than Github issue trackers) is provided and documented publicly.

**Comment by harish2704** [comment]
Hi ROCm team,
I can not understand why you are not interested in building a community.
immediately closing such a question without a single response doesn't seems to be right approach for an opensource project.

For eg: I was trying to port a cuda project ( project name is "warp-ctc" which is a CTC implementation with pytorch binding ) into ROCm.

I found 2-3 bugs in the ROCm platform and related tools, and I fixed them all .
But I need some guide lines for further development and bug reporting.

A mailing list / IRC / Matrix / gitter / slack channel for developer discussion will be a great help for people like me who would like to contribute to ROCm platform.

Please consider adding at least a IRC / Matrix chat room for developer discussions

**Comment by jpsamaroo** [comment]
Feel free to join us on Freenode (chat.freenode.net) in the #ROCm channel.
Some of us have been hanging out in there, answering the few questions we know
how to answer :)

And sorry for not updating this issue with that information! Hopefully one of
the AMD people can add that channel to the ROCm README?

**Comment by jpsamaroo** [comment]
> I can not understand why you are not interested in building a community.
immediately closing such a question without a single response doesn't seems to be right approach for an opensource project.

I wouldn't say they're not interested, but more likely that they're so busy with development work that they haven't had the time to setup things like IRC or other messaging platforms. Of course, there are still mailing lists and #radeon and #amdgpu on Freenode, it's just that these platforms aren't advertised on this repo where everyone interested in ROCm will inevitably see them.
