### ISSUE TITLE
ROCm 3.1 completely broke Davinci Resolve and Blender support

### ISSUE THREAD

**Issue by paranoidfactoid** [RadeonOpenCompute/ROCm#1030]
Because of issue #768 / #769, I've been holding back with old rocm-2.2 libs so programs like Davinci Resolve and Blender would continue to work. It's been nearly a year without resolution to this issue. Only now, with the latest system upgrade to 3.1, it's a complete fail for all OpenCL applications. For whatever reason. rocm-3.1 still doesn't work with Davinci Resolve.

AMDGPU-Pro doesn't work with it. And now the latest rocm doesn't work with it. I'm downgrading again. But I wish a dev here would look into this.

**Comment by paranoidfactoid** [comment]
OK. Rocm-3.1 goes down a new /opt directory tree. If you already have rocm-2.2 opencl libs, they'll be wiped and a symlink put in place for /opt/rocm -> /opt/rocm-3.1. So, the solution here is to wipe rocm entirely, including the old packages. Then reinstall rocm-3.1 from scratch. Then reinstall rocm-2.2 opencl and opencl-dev libs. And Davinci and blender will work again. This is continuing the completely broken situation that's prevailed for the last year. But at least it works for now.

**Comment by ableeker** [comment]
I don't know about Davinci, but 3.1 made Blender work for me. I say work, but unfortunately that's stretching it, because Cycles needed almost 2.5 hours to render the default cube scene! However, this is progress indeed, because Cycles couldn't render with ROCm OpenCL 2.10 at all, and aborted with a split kernel error message.

I'm checking out a tip I've read somewhere, which is to install ROCM, but then replace ROCm libamdocl64.so with the version included with AMDGPU-Pro. Cycles does render this way, but this is an unsupported hack, of course, and may cause other problems. I have noticed that gpuowl doesn't work anymore for instance, while it's working with normal ROCm 3.1.

Not sure if this is working in Blender either, because GPU rendering with Cycles took the same time as a CPU render...

**Comment by yugenekr** [comment]
Hey guys, what's you experience with Blender GPU render performance if to compare with/without rocm 3.1 (plus hack applied) installation?

Do I get it right you still get better performance just using amdgpu-pro driver (without rocm 3.1.)?

**Comment by Utopanic** [comment]
Rocm-dkms 3.5 broke Davinci and Blender for me, I'm on Ubuntu MATE 20.04 with Linux 5.04 running on a RX 480, with the previous version it worked fine

**Comment by KristijanZic** [comment]
It broke DR, Natron and Blender for me too. I broke it back with ROCm 2.3.

**Comment by KristijanZic** [comment]
A year after, AMD is yet to even comment on this issue. We should sue them for false advertising. They sold us all a snake oil and are continuing to sell more. If they spent just a fraction of their money they spend on marketing to do some actual development and testing they'd be in a much better position. I'm really considering a class action as my GPU is out of warranty because I waited too long hoping that they'll fix this, but now I realize we were all essentially defrauded. They took our money by falsely advertising and then said sayonara suckers..
We should also send a letter to the EU regulators to craft a legislation which would protect the customer against this kind of customer fraud because this is kind of a grey area but I'm sure that we could make it happen in 8-16 months. We'd have it regulated and we'd be protected against this kind of corporate negligence and fraud. They'd be forced to either support their product or give us refunds and slowly be pushed out of the market.

To many times we see corps releasing half bake products early with a promise of software/driver support down the line that never actually happens and the customer ends up being the victim of fraud, that's essentially what it is. We have a strong case here, and we could make it happen. I'd go as far as saying that it's our responsibility at this point to do something. Otherwise we deserve it if we keep quiet.

**Comment by ROCmSupport** [comment]
Request to track Davinci issue @ https://github.com/RadeonOpenCompute/ROCm/issues/1345
Request to track Blender issue @ https://github.com/RadeonOpenCompute/ROCm/issues/1106
