### ISSUE TITLE
errors while compiling PyTroch

### ISSUE THREAD

**Issue by Roalkege** [RadeonOpenCompute/ROCm#1036]
Hello I tried to compile ROCm/PyTorch for my RX580 but I get everytime this error and I dont know hat I have to do.
I use [this Doc ](https://rocm-documentation.readthedocs.io/en/latest/Deep_learning/Deep-learning.html#pytorch) to compile it.
![image](https://user-images.githubusercontent.com/44238399/76143531-72684700-6078-11ea-98af-2583cda06985.png)

I hope someone can help me. Or is there a precompiled image for my RX580?

**Comment by MichaelEssich** [comment]
Perhaps you have to apply this patch (not sure if it is already fixed in current version, but the last time I built PyTorch I had to apply it): https://github.com/pytorch/pytorch/commit/3a7ecd32eb7418e18146fe09dc9301076b5f0f17
If that's not the issues, maybe this guide can help: https://github.com/ROCmSoftwarePlatform/pytorch/issues/581

**Comment by Roalkege** [comment]
[pytorch/pytorch@3a7ecd3](https://github.com/pytorch/pytorch/commit/3a7ecd32eb7418e18146fe09dc9301076b5f0f17) worked for me but now I tried to check if everything is working with `PYTORCH_TEST_WITH_ROCM=1 python test/run_test.py --verbose` but I get this.
After the the compile process the script also copied a lot of files.
I also replaced `python` with `python3`
![grafik](https://user-images.githubusercontent.com/44238399/76227573-cf523180-621f-11ea-922d-be9b5097b4b4.png)

**Comment by JavascriptAddict** [comment]
Try using python3.6 instead of python3
