### ISSUE TITLE
GFX10 (Navi) Support

### ISSUE THREAD

**Issue by omerferhatt** [RadeonOpenCompute/ROCm#1061]
Hello, I asked when will Navi cards are going to be supported a couple of months ago (#926) and the answer was uncertain. Is there any update about Navi based cards? Thanks for your reply.

**Comment by valeriob01** [comment]
Long ago (six months or more) I was able to get NAVI working, but I don't remember if it was ROCm or amdgpu-pro. Anyway the performance of RX 5700 XT was inferior to Vega64.

**Comment by lrie** [comment]
https://github.com/RadeonOpenCompute/ROCm/issues/887#issuecomment-605711172

**Comment by omerferhatt** [comment]
Thank you for your answers

**Comment by Spacefish** [comment]
https://www.youtube.com/watch?v=-iYwbnvV2w0 <- works with Navi 10 (5700 XT) if you built it from source for that target!

**Comment by ROCmSupport** [comment]
Hi @omerferhatt 
Navi support will come in 2021, please stay tuned for the updates.
Thank you.

**Comment by edurenye** [comment]
Shouldn't this issue be open until the Navi support is added so we can be updated here?
Do you have any more precise date? 2021 is a full year

**Comment by omerferhatt** [comment]
They may be waiting for it to rust. It is very sad that people are waiting for support for the previous one despite the new architecture emerging. It's my fault to buy that card even though AMD says no support. So I sold it out. For a long time I'm not thinking of buying an AMD graphics card if I don't need it specifically. I am leaving this issue and I wish success to the entire ROCm family. 👍🏻

**Comment by edurenye** [comment]
I think they should add support for a graphic card in their software before they sell it, otherwise you are buying a product that is not finished. And if it lacks support of something it should be told in the box of the graphic card that you will not be able to use it with some of their software. You should not have to spend time to investigate with all their software if is compatible with the graphic card that you are buying the common sense tells me it should support everything.
