### ISSUE TITLE
TensorFlow on RX 470 8GB

### ISSUE THREAD

**Issue by bimonsubio1984** [RadeonOpenCompute/ROCm#1073]
Hello,

Please let me know:

Does RX 470 8GB card work fine with ROCm? Are there any differences compared to RX 580 except 25% drop in performance? Architectures of RX 470 and RX 580 look almost the same IMHO, though only RX 580 is mentioned as supported on ROCm page.

Except mining I would like to learn and experiment with TensorFlow on RX 470 8GB card, is it possible? Are there any limitations of RX 470 when using with TensorFlow+ROCm compared to RX 580 or may be RX 470 will not work at all (doubtfully)?

**Comment by Bengt** [comment]
Hi, @bimonsubio1984!

You are probably looking for the tensorflow rocm issue tracker:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/

Your cards use the GFX803 ISA on which Tensorflow runs buggy at best, for more details see:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/479

Personally, I ended up buying Vega GPUs. Those work fine with tensorflow, so maybe do so, too.

**Comment by bimonsubio1984** [comment]
Please suggest which models/manufacturers of Vega are the most problem free, cool, cold and quiet?

As for RX 4xx/5xx cards I guess it was Sapphire Nitro+ ?

**Comment by Bengt** [comment]
Sorry, I don't know that much about the aftermarket cards. Please do your own research on that.

I trusted Buildzoid with his VRM analysis of the reference Vega 64/56. Since the VRM on those is quite over built, I got a Vega 64 and put it under custom water using a core-only water block as my primary card. the next two are Vega 64 Liquid, which is a bit more noisy and the fourth one is a stock Vega 64 reference blower card, which is noisier still. I have another core-only water block to put on it, but in my experience machine learning rarely hits the cards so hard that the fan kicks up to annoying levels, so I haven't bothered with that. After all, modifying the base plate to fit a core-only water block and all the other mods needed to make this work take about a day, so that time investment needs to pay for itself.

I have no experience with Vega 56 compared to Vega 64 for machine learning. I figured, used Vega 64 would be more financially attractive, because the high-end variant has a more stable resell value. But again, your priorities may be different, so please make up your own mind about that.

**Comment by Laser-Cat** [comment]
Tf 1.15.2 works with my rx 470 4G card. You may or may not need to meddle with the tensorflow code abit. The inference with C API looks okay to me, not sure about training tho.

**Comment by ROCmSupport** [comment]
Thanks @bimonsubio1984 for reaching out.
ROCm does not support gfx8 devices anymore. Please follow our documentation for more details.
Thank you.
