### ISSUE TITLE
OpenCL 3.0 Released

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#1092]
https://www.khronos.org/news/press/khronos-group-releases-opencl-3.0

**Comment by Degerz** [comment]
Huge step backwards compared to OpenCL 2.0, I'll call it for what it really is which is just a rehash of OpenCL 1.2 ... 

No point in AMD even trying anymore to implement OpenCL when they have their HIP API which is so much better ...

**Comment by informatorius** [comment]
I want to see OpenCL 3.0 too. e.g. For OpenCL, since OpenCL 2.2, the cl_khr_throttle_hints extension is defined and allows to specify the throttling that's needed.
It allows to create a command queue with CL_QUEUE_THROTTLE_KHR set to CL_QUEUE_THROTTLE_LOW_KHR (4). That tells the runtime it may run in a way that's optimized, with lowest energy consumption.
