### ISSUE TITLE
Use of mainline kernel

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/ROCm#118]
Is any release of ROCm compatible with any mainline release of the Linux kernel? E.g., can I use ROCm 1.5 with kernel 4.11? If not, what are the plans for ROCm to be mainlined?

**Comment by gstoner** [comment]
1.5 uses the 4.9 kernel,  we are in the process of upstreaming all the key components.   With 1.6 we finally have full DKMS support.  We full engineering team dedicated to ROCm maintaining it.
On May 5, 2017, at 7:19 AM, almson <notifications@github.com<mailto:notifications@github.com>> wro


Is any release of ROCm compatible with any mainline release of the Linux kernel? E.g., can I use ROCm 1.5 with kernel 4.11? If not, what are the plans for ROCm to be mainlined?

**Comment by grmat** [comment]
@gstoner thanks for the info. So you don't plan going upstream with ROCK for 4.12?

**Comment by gstoner** [comment]
Merge windows for Linux kernel are delicate balance,  we are working on getting all the code where applicable up streamed

**Comment by reanimastudios** [comment]
In short, wait until the 1.6 release and verification that the mainline kernel has full support for it. Got it.

**Comment by ernstp** [comment]
Although you have Ryzen support, Ryzen processors really like a 4.10 kernel. So this will be good for Ryzen users too...

**Comment by gstoner** [comment]
It in the plans.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Fri, Jun 2, 2017 at 11:59 AM +0100, "Ernst Sjöstrand" <notifications@github.com<mailto:notifications@github.com>> wrote:


Although you have Ryzen support, Ryzen processors really like a 4.10 kernel. So this will be good for Ryzen users too...

**Comment by iavael** [comment]
What version of mainline kernel is required to run rocm?

**Comment by gstoner** [comment]
It best to load Ubuntu 16.04 and follow the install instruction,  we have new instruction at 
https://rocm.github.io/ROCmInstall.html   Currently ROCm uses the 4.9 Linux kernel.   Note for Ubuntu, it best to use our kernel.     We have base 4.11 Kernel update in our internal mainline, it under test now.  

We are working with the community to upstream the extra driver components we need.

**Comment by iavael** [comment]
@gstoner I thought, that this issue was closed, because all needed patches were upstreamed to mainline. So support of mainline kernel is not ready yet? If it's so, can you reopen this issue, please?

**Comment by reanimastudios** [comment]
Mainline kernel support hasn't been updated or it wouldn't be necessary 
for the custom 4.9 kernel and I could just run dkms directly via Debian 
and have it hooked into Debian Sid.

I sure am looking forward to the OpenCL stack from ROCm and Mesa since 
the OpenGL track and later Vulkan support [another interesting topic 
that will come up when AMD is ready with their Vulkan stack vs. RADV] 
since that is the direction AMD has committed to achieving relies on the 
OpenCL stack from ROCm, and not Gallium.

However, I sure as hell am never going to use Ubuntu proper so the only 
full stack that AMD offers in deb format off AMD is out of reach for me. 
I'm a happy AMD investor in stock and hardware but an irritated Linux 
user. I am fully aware of software release schedules in my career.

My other systems are OS X and as an ex-NeXT/Apple engineer I understand 
the need to satisfy the Enterprise markets first and legacy professional 
markets.

With the increased visibility and growth in this upcoming Q10 I urge AMD 
to double the size of their staff for this endeavor. It's paramount that 
the ROCm initiative be mature, across Windows and Linux, and wise if 
they extend their business relationship with Apple to do everything 
possible for the iMac Pro, Mac Pro and future potential Zen systems to 
achieve a long term stable corporation.

- Marc J. Driftmeyer

**Comment by gstoner** [comment]
Guys I wish we could service all the flavor of Linux, but we can not currently. Marc hit the nail on the head engineering and testing staff is critical to broadening our support.  Remember we balancing supporting new silicon ( Vega10, EPYC, Threadripper, Ryzen, Power, ARM AArch64 etc)  new capabilities, new libraries, new application, improving the software we have already put in place.  All on moving target the Linux Kernel.    

Now it would have been fun to have NextOS and what we doing with ROCm today, plus that engineering team help exploit what we can do with EPYC   Naples is game changer and it  Have 4 Vega10 GPU's on Single socket with 32 cores 64 threads and 8 channel of 4TB memory up  200-250 GB/s bandwidth. 

I give you a preview for 1.7  release  REHL/Centos 7.3, Ubuntu, Fedora via DKMS.  Once we have base DKMS in place we can look at qualifying other Linux Distro. This is the last 1.x series to satisfy this requirement by late mid-summer,  then we focused on 2.0 release for the fall.   

Here is a list of all the packages we rolled out with ROcm 1.6, https://github.com/ROCm/ROCm.github.io/blob/master/ROCmLinuxpackages.md

**Comment by iavael** [comment]
@gstoner  I just wanted to have some place to keep track on effort to run rocm on distro/mainline/custom kernel (in-tree, dkms or any other way). And I thought that this issue is such place. If it's not, then could you tell me where to look?

**Comment by gstoner** [comment]
I will build something on ROCm.github.io to talk about how to build custom kernels.  I have been talking to the Linux team about not just dropping a single kernel but breaking out the major components of ROCm kernel driver as separate projects so it easier to understand what is really changing in the kernel.  Also, make it easier to port this to other OS.     Short of this, I set aside some time documentation on the website describing the kernel changes and changes Kernel graphics driver.   

I have been looking at this anyone since I want to work with eBPF with PERF on a EPIC system with Vega10.

**Comment by almson** [comment]
@gstoner The way GitHub works, is that if there is a feature request, then it exists as an open issue until the feature request is implemented. There are multiple reasons for this, including the notification mechanism that GitHub has.

So, reopen this issue.

**Comment by marmistrz** [comment]
Yeah, keeping the issue closed suggests it's a wontfix and, as far as I understand, it's the opposite - on the roadmap.

**Comment by gstoner** [comment]
We are working on DKMS solution,  for the stack so no it not that we not going to do this, Patience we doing a lot of work with a small team.   We also have REHL/CENTOS and SUSE support on the Roadmap,  REHL/CENTOS is coming first. 

@almson  I know you have strong opinion, but moderation is how GitHub works, this tread has been moderated

**Comment by marmistrz** [comment]
@gstoner I read the whole thread so I perfectly know this. I'm just signaling that the issue being closed miscommunicates:

* open = just reported / todo / in progress / awaiting merge / ...
* closed = fixed / wontfix / invalid / duplicate / obsolete / notabug

This issue clearly should be open, since you're working on it.

**Comment by gstoner** [comment]
We already have a solution,  Base Linux kernel the same for AMDGPU and AMDGPUpro the later use DKMS and Kernel Compatibility layer.   Also, we are upstreaming all the core foundation update for ROCm into the Linux kernel so it will be maintained in each update. 

The issue is closed

**Comment by reanimastudios** [comment]
I have a simple request: Close this after this is upstreamed and mainlined into the Linux Kernel. At the rate AMDGPU and OpenCL is evolving we might be ready for Navi.

- Marc

Marc Jeffrey Driftmeyer
Founder & CEO of Reanimality Studios LLC
Cell: (509) 435-5212
url: https://www.reanimastudios.com <https://www.reanimastudios.com/>
url: https://www.holoworlds.net <https://www.holoworlds.net/>
email: mjd@reanimality.com <mailto:mjd@reanimality.com>
email: mjd@holoworlds.net <mailto:mjd@holoworlds.net>
