### ISSUE TITLE
Missing Ubuntu 20.04 focal distribution in http://repo.radeon.com/rocm/apt/debian/dists

### ISSUE THREAD

**Issue by jmsjr** [RadeonOpenCompute/ROCm#1201]
As per #1074 and as per on-line documentation at https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html, both says that Ubuntu 20.04 is now officially supported.

However, both :
1) The on-line section at https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu 
2) And the repo at http://repo.radeon.com/rocm/apt/debian/dists/

... indicates that only Ubuntu Xenial ( 16.04 ) is supported.

Will there be a separate instructions or directory for Ubuntu 20.04 ( Focal Fossa ) ?

**Comment by YifeiLuDublin** [comment]
I used rocm-dkms package in the xenial folder for my ubuntu 20.04.1 and VEGA 64.
So far my hip code seems working fine

**Comment by rkothako** [comment]
@jmsjr
This issue is already notified internally and will be fixed in ROCm 3.8.

xenial is the space name here which points to all packages in ROCm repo. Actually there is no issue w.r.to functionality front.
As ROCm dropped official support of Ubuntu 16.04, we have plans to change the space name to "focal" instead of "xenial".
Next release will have this change.

**Comment by rkothako** [comment]
Yes @YifeiLuDublin, Its the same and name is only the difference.
We can use the same path for all supported versions of Ubuntu.

**Comment by ROCmSupport** [comment]
Hi @jmsjr 
Due to security constraints, its still showing xenial.
Only naming is the issue, but functionally its same only. We have plans to change the name from xenial to focal/bionic in future. But its low priority task and we are working on it too.
