### ISSUE TITLE
Not possible to build ROCm from source code

### ISSUE THREAD

**Issue by niso** [RadeonOpenCompute/ROCm#1238]
System information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian buster
    Python version: 3.7
    ROCm/MIOpen version: 3.8
    GPU model and memory: Vega 64

Describe the problem
Core components nor metapackages are not present when using the instructions below:
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#downloading-the-rocm-source-code

Since the new deb packages depend on python 3.8, you have blocked the possibility to all Debian buster users.
Since you don't have older versions in your repository, we can't downgrade to 3.7.
Since your instructions to build the library from source are not working we are totally stuck.

    Do we have any way (apart from reinstall a new OS) to have a working system?

**Comment by Rmalavally** [comment]
Thank you for reaching out and bringing the issue to our attention.

We have passed on the relevant information you have shared to our team and will keep you updated once we hear from them.

AMD ROCm Documentation Team

**Comment by baryluk** [comment]
You can modify the control files to use python3.7 libraries. It should work. Or update to Debian testing (bullseye).

Debian is not officially supported, but another possibility is to add `python3.7 | python3.8` instead of just `python3.8` where required. And when using `python3 >= xx", use `python3 >= 3.7.0`. I don't guarantee it will work with python3.7, as there are some syntax and ABI extensions present in 3.8 that are not available in 3.7. But I expect no code in ROCm repos really use these new syntax features (like assignment expressions, positional-only parameters, vectorcall ABI, final methods, typed dicts, etc), so there is high chance of this working.

**Comment by rkothako** [comment]
Hi @niso 
Can you please close this ticket, if its not relevant anymore.
Thank you.
