### ISSUE TITLE
Where is MIOpen 1.0?

### ISSUE THREAD

**Issue by oscarbg** [RadeonOpenCompute/ROCm#133]
Hi seen 
"Planned for June 29th rollout, the ROCm 1.6 software platform with performance improvements and now support for MIOpen 1.0 is scalable and fully open source"
can't find repo for MIOpen.. can point me where to obtain it?
or it's coming on June 29 with ROCM 1.6?
also ROCM 1.6 will support Vega Founders Edition cards? and Radeon Vega cards coming @ SIGGRAPH?
thanks..

**Comment by gstoner** [comment]
It is June 24th today,  we will release it on June 29th in the ROCm Software Platform Repo.  Thank your for your patience.

**Comment by oscarbg** [comment]
Hi,
thanks..
just see https://github.com/ROCmSoftwarePlatform/MIOpenGEMM
is that the full MIOpen library? I say that because I see:
"Instructions for building the documentation are identical to those for MIOpen" which points to:
https://github.com/AMDComputeLibraries/MLOpen#building-the-documentation
which doesn't exist..
just pointing out..

**Comment by gstoner** [comment]
It is an optimized set of Gemm solvers  MIOpen source is coming



On Jun 30, 2017, at 5:40 PM, Oscar Barenys <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
thanks..
just see https://github.com/ROCmSoftwarePlatform/MIOpenGEMM
is that the full MIOpen library? I say that because I see:
"Instructions for building the documentation are identical to those for MIOpen" which points to:
https://github.com/AMDComputeLibraries/MLOpen#building-the-documentation
which doesn't exist..
just pointing out..
