### ISSUE TITLE
CUB Libraries and Thrust

### ISSUE THREAD

**Issue by acyeh** [RadeonOpenCompute/ROCm#135]
I was wondering if there were equivalents for the CUB/Thrust Libraries available for ROCm?

Namely, I'm searching for alternative methods for:

1. cub::DeviceReduce::ArgMax
2. cub::DeviceReduce::ArgMin
3. cub::DeviceReduce::Max
4. cub::DeviceReduce::Sum
5. cub::DeviceRadixSort::SortKeys
6. cub::DeviceScan::InclusiveSum

**Comment by nevion** [comment]
I don't think they're on the drawing board yet.  Keep pressure on and maybe they'll eventually figure it out.  Libraries like this are required for researchers to be productive.

CUB under the covers is definitely nastier than on the top and would probably be difficult to support upstream, but since it's FOSS... maybe they can work it out.

**Comment by gstoner** [comment]
CUB and Thurst Ports are under development. We have seen some nice progress on them.   Remember we young project and we have competing priorities, capped capacity for man/engineering hours.    We are also working on PSTL based libraries for HCC.

**Comment by nevion** [comment]
just FYI - I think CUB is generally more useful than most of thrust/PSTL after a point.  What I've seen is most people tend only use the stl like libraries for any of sort (including key variants), scatter, gather, and reduction.  Not too much else as complicated stuff always finds itself in new kernels for huge relative speedups.  Point being that it's easy to hit diminishing returns after just a few functions in those libraries.

**Comment by gstoner** [comment]
We still keep running into Thurst in our Ports so we decided to knock it out.   CUB is more interested we agree.
