### ISSUE TITLE
Support for RDNA and RDNA 2?

### ISSUE THREAD

**Issue by OliverSmeeton** [RadeonOpenCompute/ROCm#1406]
As far as I can tell ROCm doesn't support RDNA or RDNA 2 could this be added? As I would like to use opencl on my rx 5600 xt without using the proprietary drivers.

**Comment by xuhuisheng** [comment]
Just like metioned in https://github.com/RadeonOpenCompute/ROCm/issues/887, AMD said RDNA will get offcial support in 2021. No more details.

It is appreciated that AMD could support some docs like WIKI to show the plan for RDNA. Otherwise there will be new issues created for RDNA.
@ROCmSupport Please consider my advice.

**Comment by ROCmSupport** [comment]
Thanks @OliverSmeeton for reaching us.

Hi @xuhuisheng, thanks for passing the details.
Yes, we have plans to add support in this year. Please stay tuned.
We can not add details of future plans in our wiki/docs as per the process.
Hope you got it.
Thank you.

**Comment by AGenchev** [comment]
I hope you have planned to support APUs as well, because you're losing money in the niche of products like Nvidia Jetson in the last 4 years.
