### ISSUE TITLE
Polaris "failed to send message" errors during boot. 

### ISSUE THREAD

**Issue by jstefanop** [RadeonOpenCompute/ROCm#146]
On a fresh install of ROCm 1.6 on top of Ubuntu 16.04 we are getting the messages below during boot after ring tests. Each GPU hangs for about 10 seconds and boot continues normally. 

Card seems to be initialized and working properly post boot regardless (full openCL performance on par with AMDGPU-PRO). 

This issue is not present during Vega FE boot

`[    3.058782] amdgpu 0000:01:00.0: fb0: amdgpudrmfb frame buffer device
[    3.485773] amdgpu: [powerplay] 
                failed to send message 260 ret is 0 
[    4.310558] amdgpu: [powerplay] 
                failed to send pre message 260 ret is 0 
[    4.723086] amdgpu: [powerplay] 
                failed to send message 260 ret is 0 
[    5.547875] amdgpu: [powerplay] 
                failed to send pre message 260 ret is 0 
[    5.960395] amdgpu: [powerplay] 
                failed to send message 260 ret is 0 
[    6.785188] amdgpu: [powerplay] 
                failed to send pre message 260 ret is 0 
[    7.197712] amdgpu: [powerplay] 
                failed to send message 260 ret is 0 
[    8.022497] amdgpu: [powerplay] 
                failed to send pre message 260 ret is 0 
[    8.435022] amdgpu: [powerplay] 
                failed to send message 260 ret is 0 
[    9.259809] amdgpu: [powerplay] 
                failed to send pre message 260 ret is 0 
[    9.672330] amdgpu: [powerplay] 
                failed to send message 260 ret is 0 
[   10.502892] amdgpu: [powerplay] 
                failed to send pre message 260 ret is 0 
[   10.924276] amdgpu: [powerplay] 
                failed to send message 260 ret is 0 
[   10.938191] kfd kfd: Allocated 3969056 bytes on gart for device 1002:67df
[   11.346839] amdgpu: [powerplay] 
                failed to send pre message 15b ret is 0 
[   11.767822] amdgpu: [powerplay] 
                failed to send message 15b ret is 0 
[   12.196446] amdgpu: [powerplay] 
                failed to send pre message 155 ret is 0 
[   12.618252] amdgpu: [powerplay] 
                failed to send message 155 ret is 0 
[   12.628554] Virtual CRAT table created for GPU
[   12.630970] Parsing CRAT table with 1 nodes
[   12.632391] Creating topology SYSFS entries
[   12.633893] Topology: Add dGPU node [0x67df:0x1002]
[   12.635339] kfd kfd: Reserved 2 pages for cwsr.
[   12.636769] kfd kfd: added device 1002:67df
[   12.638159] [drm] Initialized amdgpu 3.16.0 20150101 for 0000:01:00.0 on minor 0
[   12.641308] ACPI: Video Device [GFX0] (multi-head: yes  rom: no  post: no)
[   12.643153] acpi device:16: registered as cooling_device9
[   12.644718] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input9
[   12.646381] [drm] Initialized i915 1.6.0 20160919 for 0000:00:02.0 on minor 1`

**Comment by gstoner** [comment]
Your sitting at base clock,  there is power play library failure due to VBIOS update.

Greg
On Jul 3, 2017, at 5:09 PM, jstefanop <notifications@github.com<mailto:notifications@github.com>> wrote:


On a fresh install of ROCm 1.6 on top of Ubuntu 16.04 we are getting the messages below during boot after ring tests. Each GPU hangs for about 10 seconds and boot continues normally.

Card seems to be initialized and working properly post boot regardless (full openCL performance on par with AMDGPU-PRO).

This issue is not present during Vega FE boot

[ 3.058782] amdgpu 0000:01:00.0: fb0: amdgpudrmfb frame buffer device [ 3.485773] amdgpu: [powerplay] failed to send message 260 ret is 0 [ 4.310558] amdgpu: [powerplay] failed to send pre message 260 ret is 0 [ 4.723086] amdgpu: [powerplay] failed to send message 260 ret is 0 [ 5.547875] amdgpu: [powerplay] failed to send pre message 260 ret is 0 [ 5.960395] amdgpu: [powerplay] failed to send message 260 ret is 0 [ 6.785188] amdgpu: [powerplay] failed to send pre message 260 ret is 0 [ 7.197712] amdgpu: [powerplay] failed to send message 260 ret is 0 [ 8.022497] amdgpu: [powerplay] failed to send pre message 260 ret is 0 [ 8.435022] amdgpu: [powerplay] failed to send message 260 ret is 0 [ 9.259809] amdgpu: [powerplay] failed to send pre message 260 ret is 0 [ 9.672330] amdgpu: [powerplay] failed to send message 260 ret is 0 [ 10.502892] amdgpu: [powerplay] failed to send pre message 260 ret is 0 [ 10.924276] amdgpu: [powerplay] failed to send message 260 ret is 0 [ 10.938191] kfd kfd: Allocated 3969056 bytes on gart for device 1002:67df [ 11.346839] amdgpu: [powerplay] failed to send pre message 15b ret is 0 [ 11.767822] amdgpu: [powerplay] failed to send message 15b ret is 0 [ 12.196446] amdgpu: [powerplay] failed to send pre message 155 ret is 0 [ 12.618252] amdgpu: [powerplay] failed to send message 155 ret is 0 [ 12.628554] Virtual CRAT table created for GPU [ 12.630970] Parsing CRAT table with 1 nodes [ 12.632391] Creating topology SYSFS entries [ 12.633893] Topology: Add dGPU node [0x67df:0x1002] [ 12.635339] kfd kfd: Reserved 2 pages for cwsr. [ 12.636769] kfd kfd: added device 1002:67df [ 12.638159] [drm] Initialized amdgpu 3.16.0 20150101 for 0000:01:00.0 on minor 0 [ 12.641308] ACPI: Video Device [GFX0] (multi-head: yes rom: no post: no) [ 12.643153] acpi device:16: registered as cooling_device9 [ 12.644718] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input9 [ 12.646381] [drm] Initialized i915 1.6.0 20160919 for 0000:00:02.0 on minor 1

**Comment by gstoner** [comment]
If PPlib fails we drop the clock to minimum frequency.  around 900 mhz or less. on vega10,  which why your seeing low performance.  we have no way for the Driver to drive the clock up with the driver since PPLIB interacts with System mangment unit which controls the clock. We will get a patch out.

**Comment by jstefanop** [comment]
@gstoner this issue is only present on Polaris based cards. Even so, there is no performance impact on the polaris cards. The only real impact is slow boot since, if there are several cards on the system each card takes 10+ seconds to boot. 

This issue is NOT present on Vega FE, Vega FE boots properly and is running at 1600mhz, verified by both smi utility and power consumption. This issue is not the cause of very low Vega performance.

**Comment by gstoner** [comment]
Looking at the slow boot time is there more than 10 GPU in the system.

**Comment by jstefanop** [comment]
Our systems are designed for 16+ but this issue is present even on normal boards with a single gpu running ROCm kernel. Every Polaris based gpu hangs for ~ 10 seconds as amdgpu drm posts them.

**Comment by gstoner** [comment]
How many PLX, and how deep, I mean are you cascading PLX switch like tree 2 to 3 layer deep.

Also

Greg
On Jul 4, 2017, at 3:20 PM, jstefanop <notifications@github.com<mailto:notifications@github.com>> wrote:


Our systems are designed for 16+ but this issue is present even on normal boards with a single gpu running ROCm kernel. Every Polaris based gpu hangs for ~ 10 seconds as amdgpu drm posts them.

**Comment by jstefanop** [comment]
Only two switches off the root complex. Each switch feeds 8 GPUs. Either way this issue is present with the GPU plugged directly into the root 16x lanes coming from CPU. 

I will try the ryzen setup later to rule out any issues with kabylake i3 we are using on our test bench. 

Are you able to reproduce the issue with your systems?

**Comment by gstoner** [comment]
What are the exact plx you are using?  We only have plx8747 based systems.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Tue, Jul 4, 2017 at 3:39 PM -0500, "jstefanop" <notifications@github.com<mailto:notifications@github.com>> wrote:


Only two switches off the root complex. Each switch feeds 8 GPUs. Either way this issue is present with the GPU plugged directly into the root 16x lanes coming from CPU.

I will try the ryzen setup later to rule out any issues with kabylake i3 we are using on our test bench.

Are you able to reproduce the issue with your systems?

**Comment by jstefanop** [comment]
Lets forget our custom systems for now, since we are testing on the simplest system possible to reduce variables. 

We can confirm this issue is present on your Ryzen platform as well, so its definitely a driver bug on the ROCm stack. 

Here is the exact test bench rig

Ryzen 5 1400
ASRock AB350 Pro 4
16 GB Dual Channel Corsair 2400 RAM
Power Color 570 4GB on main 16x slot (pcie lanes from CPU) (issue happens across multiple test cards on polaris line from 470/480/580s)
Fresh 16.04.02 with ROCm kernel

**Comment by gstoner** [comment]
We use Ryzen, EPYC,, Ryzen ThreadRipper, Intel Xeon E5, Intel Core I7, I5 for testing.   We double check your finding to see if there is an issue is an issue or is a motherboard system bios issue.  

ROCm was Enterprise Server focused, the primary server system under test is SuperMicro SYS-1028 GQ, SYS-7048, SYS-4028 with Xeon E5 v3 & v4 processors. We also have a number Inventec P45 EPYC server and K888 Intel Xeon E5 systems under test.  We also test Lenovo, Dell and HP servers.

**Comment by jstefanop** [comment]
@gstoner yea like i mentioned its not that huge of an issue, since Polaris has its own consumer stack that works fine on all our systems, and this issue is not present on vega with this driver stack. Only reason I mention it is because Polaris cards are officially supported by the ROCm stack.

**Comment by gstoner** [comment]
We are going to dig in on Polaris since MI6 is Polaris 10 based.    One thing we  I need to evaluate is there is the issue in the VBIOS on the RX580 or this device ID issue for that card.    We not in Markham so we do not alway get the newest consumer hardware

**Comment by gstoner** [comment]
Also I am going to check the performance  Vega OpenCL - Windows vs ROCm, plus Polaris and Fiji  Windows vs ROCm vs 17.20
On Jul 5, 2017, at 8:03 PM, jstefanop <notifications@github.com<mailto:notifications@github.com>> wrote:


@gstoner<https://github.com/gstoner> yea like i mentioned its not that huge of an issue, since Polaris has its own consumer stack that works fine on all our systems, and this issue is not present on vega with this driver stack. Only reason I mention it is because Polaris cards are officially supported by the ROCm stack.

**Comment by jstefanop** [comment]
Was this resolved?

**Comment by gstoner** [comment]
We found the issue it on MSI motherboard there is APCI issue in the Linux kernel, we have back patch in 1.6.1

**Comment by gstoner** [comment]
The SBIOS issue and Base Linux kernel issue not ROCm

**Comment by maxsolyaris** [comment]
I have same issue. Do you have some way to resolve this?

**Comment by gstoner** [comment]
@maxsolyaris. We updated the 4.11 Linux kernel which fixed this issue, on MSI motherboard you also need to update the SBIOS.

**Comment by rhlug** [comment]
FWIW - I'm on latest bios on my MSI X370 A4 Gaming Plus (Sept 21 bios), and I still see these errors on bootup w/ RX470 and RX570 against the 4.11 rocm kernel.

**Comment by delbabrour** [comment]
+1 i have this Issue on Msi z270-A Pro only on modded Bios on 570/580
Bios Update didn't Help,

Kernel needs to be updated to 4.14 at least

**Comment by duall** [comment]
Updated both kernel 4.14 and BIOS for H110 BTC+. Still having this crash when restarting.

**Comment by gstoner** [comment]
4.15 will be part of our next release.  Note 4.14 Linux kernel does not have all the feature need for DGPU yet to run ROCm.  4.16 look to  first upstream Linux kernel that have everything you need 

Greg

**Comment by derdigge** [comment]
dear all. i stompled in googling this error. Iam on MSI Z170A Gaming M5 with 7x rx580 and 2~3 of them sitting at base clock(stock bios). A modified bios can not boot at all with linux.(arch)

is there a way to handle this issue?

**Comment by fresm** [comment]
I'm using Kernel 4.15.0-rc7 (!) and still getting error messages from my RX 460:
```
amdgpu: [powerplay] 
failed to send message 309 ret is 254
```
```
amdgpu: [powerplay] 
failed to send pre message 14e ret is 254 
```

**Comment by victimsofgaybullying** [comment]
Yeah Polaris 11 (and 21) RX 460-580 seems to be affected by this but not all bioses. I've made a workaround using lm_sensors that I've documented on the msi forums.

https://forum-en.msi.com/index.php?topic=298468.0

What I really want to hear from @gstoner on exactly what MSI support has fessed up to here in relation to their motherboard ACPI code. They tend to only release beta bios fixes when customers for bugs and their website bioses are years out of date and horribly broken. Intel Rapid Start was broken on my motherboard BIOS and they had to make an alpha patch. I may need to RTFM on how to cook my own AMI bios to update it myself using leaked AMI developer tools.

The good news however is that AMD's new DC driver in 4.15rc[0-8] that can also be used on Polaris 10/11 is said to have fixed this issue as well.

It's also worth reading this freedesktop ticket.
https://bugs.freedesktop.org/show_bug.cgi?id=100443#c37

**Comment by Ben-and-Ellen** [comment]
I'm seeing lots of these following errors on my ASUS B250 MINING EXPERT LGA 1151 Intel B250 HDMI SATA 6Gb/s USB 3.1 ATX Intel Motherboard:

Mar 02 18:37:41 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP08.PXSX._DSM: Argum
Mar 02 18:37:41 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP08.PXSX._DSM: Argum
Mar 02 18:37:42 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP12.PXSX._DSM: Argum
Mar 02 18:37:42 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP12.PXSX._DSM: Argum
Mar 02 18:37:42 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP12.PXSX._DSM: Argum
Mar 02 18:37:42 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP12.PXSX._DSM: Argum
Mar 02 18:37:42 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP12.PXSX._DSM: Argum
Mar 02 18:37:42 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP12.PXSX._DSM: Argum
Mar 02 18:37:42 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP12.PXSX._DSM: Argum
Mar 02 17:28:17 u-miner-1 kernel: ACPI Warning: \_SB_.PCI0.RP12.PXSX._DSM: Argum
                                   failed to send message 260 ret is 0
Mar 02 10:35:52 u-miner-1 kernel: amdgpu: [powerplay]
Mar 02 10:35:52 u-miner-1 kernel: amdgpu: [powerplay]
                                   failed to send message 15b ret is 0
Mar 02 10:35:52 u-miner-1 kernel: amdgpu: [powerplay]
                                   failed to send pre message 155 ret is 0
Mar 02 10:35:52 u-miner-1 kernel: amdgpu: [powerplay]
                                   failed to send message 155 ret is 0
Mar 02 10:35:52 u-miner-1 kernel: amdgpu: [powerplay]
                                   failed to send pre message 260 ret is 0

I'm using Ubuntu 16.04 LTS
4.4.0-112-generic

Ben

**Comment by gstoner** [comment]
Use the 4.13 Linux kernel

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Asutorufa** [comment]
Same problem

```
Jun  3 15:51:38 asutorufa-Ubuntu kernel: [   39.785164] amdgpu: [powerplay] DPM is already running
Jun  3 15:51:38 asutorufa-Ubuntu kernel: [   39.790440] amdgpu: [powerplay] 
Jun  3 15:51:38 asutorufa-Ubuntu kernel: [   39.790440]  failed to send message 309 ret is 254 
Jun  3 15:51:38 asutorufa-Ubuntu kernel: [   39.790464] amdgpu: [powerplay] 
Jun  3 15:51:38 asutorufa-Ubuntu kernel: [   39.790464]  failed to send pre message 14e ret is 254 
```

**Comment by Joe-Lapetoire** [comment]
same problem...
Linux 4.4.0-128
Rocm 1.8

**Comment by NinjaNate** [comment]
I might have figured this out for the B250 mining expert on ubuntu 16.04. If I had a card plugged into the primary A1 slot (the first x16/full size) while mining I would get these errors and rocm-smi would timeout on the card in that particular slot (while throwing more of these errors). But if I don't use it, everything is happy. Note: I am using an older AMDGPU Pro driver (17.40)  and I'm still on the 4.10 kernel, but it's crunching away happily now. So not sure if it's related at all or what it doesn't like about that first x16 slot (did not try the second either) but might be related?
