### ISSUE TITLE
ROCm Navi 10 Support in 2021

### ISSUE THREAD

**Issue by waltherwj** [RadeonOpenCompute/ROCm#1465]
Hello,

Pytorch just recently (1 month ago) officially started supporting ROCm as an option. I've seen dozens of threads asking for ROCm support, or at least a decent workaround for the Navi 10, and I found  this [closed issue](https://github.com/RadeonOpenCompute/ROCm/issues/1061) with information that support for Navi would be added in 2021.

Is there any new information about when that would be? 

People have been waiting for a long time for this to be added, and with the short supply of consumer gpus in the market in general right now, people cannot just get a cuda capable card easily, so if there is any build that does have support for it, this would be the perfect moment to release it.

**Comment by ROCmSupport** [comment]
Thanks @waltherwj for reaching out.
As we mentioned in the previous threads, Navi support will come very soon.
But I can not comment/say like specific series of Navi right now as I do not have much information due to security reasons connected. But some series of Navi will come asap.
I know that internal validation is happening right now.
Thank you.
