### ISSUE TITLE
Ubuntu 18.04.5 LTS：The KFD-related kernel was not successfully installed

### ISSUE THREAD

**Issue by gp1322719830** [RadeonOpenCompute/ROCm#1523]
**Question 1**
"lsmod | grep kfd" has no content.

**Question 2**
How to install KFD-related linux kernel?

**Comment by ROCmSupport** [comment]
Hi @gp1322719830 
Thanks for reaching out.

lsmod | grep kfd --> I dont think it will show results because kfd is not a module. Instead you can try with amdgpu modules like this: lsmod | grep amdgpu

If you wish to check on rocm dkms kernel, do like this: sudo dpkg -l | grep rock-dkms (which will show both kfd and firmware packages)

For ex:
taccuser@taccuser-GA-990FXA-UD5:~$ sudo dpkg -l | grep rock-dkms
[sudo] password for taccuser:
ii  rock-dkms                                  1:4.3-34                              all          amdgpu driver in DKMS format.
ii  rock-dkms-firmware                         1:4.3-34                              all          firmware blobs used by amdgpu driver in DKMS format

**Comment by gp1322719830** [comment]
Solved,thanks!
