### ISSUE TITLE
ROCm 4.3+docker - using a different driver version?

### ISSUE THREAD

**Issue by jammm** [RadeonOpenCompute/ROCm#1545]
Hi @ROCmSupport ,

I would like to use ROCm 4.3 with docker, but using a different driver that's usually provided for bare-metal (non-docker) machines, e.g., the 21.20 driver https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-21-20

I tried installing it myself on a docker container, but clinfo doesn't seem to detect the instances, and there's also the issue of update-initramfs command not found, which seems to be used by the driver installer there. Is there any way I can use the 21.20 driver within a docker container setup with ROCm ?

**Comment by ROCmSupport** [comment]
Hi @jammm 
Thanks for reaching out.
As per the definition of docker, all user space/mode components can be kept in a docker container, because docker container also runs on kernel. So we can not install/use kernel components/packages inside docker container, which is not possible.
So recommend to use stock kernel + install any kernel driver like amdgpu-pro or rocm kernel (rock-dkms and rock-dkms-firmware) on top of it and then run the docker container.
hope this helps.
Thank you.

**Comment by bd4** [comment]
Alternatively, you could run ROCm in a KVM virtual machine instead of in docker, and passthrough the AMD GPU to the KVM instance with vfio-pci. This is fairly involved though, and on top of what is usually required e.g. for passing through an nvidia gpu to CUDA, it also requires code changes and some monkeying with setpci after booting the virtual machine, described here: https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/issues/100. If you can, installing the desired driver on host and using it from docker is much simpler.

**Comment by ROCmSupport** [comment]
> 
> 
> Thanks @ROCmSupport !
> So if I understood correctly, I can install say, driver version 21.20 on the host machine, and then run a docker container with rocm 4.3 on it?

Yes, you can. But I have not tried like 21.20 on host + 4.3 docker container so far. Most likely it works, you can give a try.
Instead I tried 4.3 on host + 4.3 docker container.

**Comment by ROCmSupport** [comment]
Hi @jammm 
Feel free to close this ticket, if you feel that you have gotten the desired solution.
Thank you.

**Comment by jammm** [comment]
Thanks!

**Comment by jammm** [comment]
Thanks!
