### ISSUE TITLE
Radeon VII mining rate increase with old ROCm 3.3

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#1556]
- Previous system: Ubuntu 20.04
- Previous ROCm version: 4.2

- New System: Ubuntu 18.04
- New ROCm version: 3.3

Ethereum mining rate increase from 80 MH/s to 86 MH/s.

**Comment by ROCmSupport** [comment]
Hi @valeriob01 
Thanks for reaching out.
ROCm 3.3 is very old and the latest ROCm version is 4.3. Not sure why are you comparing 3.3 and 4.2.
Because between these 3.3 and 4.2, 9 more releases are there. 
So to understand and solve the problem better, I request you to reduce the gap between 3.3 and 4.2 and share the better information.
And also request you to share me the exact steps to reproduce the problem.
Thank you.

**Comment by valeriob01** [comment]
How you concluded that there is a problem?
This is only a mere mining rate comparison !
