### ISSUE TITLE
Latest ROCm 4.5, GFX8 support?

### ISSUE THREAD

**Issue by ramin-raeisi** [RadeonOpenCompute/ROCm#1695]
To whom it may concern,

Is there any GFX8 GPU is supported in ROCm 4.5? Like AMD Radeon RX 580 or any other one?

Actually, I want to have the minimum cost possible for my POC.

Thank you in advance

**Comment by ROCmSupport** [comment]
Hi @ramin-raeisi 
Thanks for reaching out.
Currently ROCm does not support gfx8 anymore. Hope this helps.
Thank you.

**Comment by ramin-raeisi** [comment]
Thanks for getting back to me, even just for HIP?

**Comment by xuhuisheng** [comment]
If you want to run larest rocm on gfx803, you need do some patch. https://github.com/xuhuisheng/rocm-build/tree/master/gfx803

**Comment by Moading** [comment]
@xuhuisheng thanks for your work to get gfx803 working again. I have seen your posts before but I never tried to reproduce.
Have you done any verification with hip examples? I am asking because the fact that the GPU shows up in clinfo or rocminfo does not mean it produces correct results.
Could you post the os and kernel you are using?
Thanks again!

@ROCmSupport could you please re-open this issue because the discussion is still ongoing

**Comment by xuhuisheng** [comment]
@Moading 
I uploaded some codes on gfx803, including hip, rocblas, miopen. <https://github.com/xuhuisheng/rocm-build/tree/master/check>
And I can run small samples with pytorch and tensorflow on gfx803. basicly, just mnist.

And cgmb said there are some testcases failed, but I had no enough time to dig recently.
