### ISSUE TITLE
Order about building ROCm from source

### ISSUE THREAD

**Issue by lintcoder** [RadeonOpenCompute/ROCm#177]
Recently I want to build the whole ROCm from source code,  since there are so many repos and no clear steps, it's difficult for me to decide the right order to build the whole project. Here is my opinion about the order as follows,  each represents one repo in ROCm, please tell me if it's right ? @gstoner 

1. ROCK-Kernel-Driver
2. ROCT-Thunk-Interface
3. ROCR-Runtime 
4. ROCm-Device-Libs
5. compiler-runtime
6. HCC
7. HIP
8. ROC-smi
9. ATMI

**Comment by gstoner** [comment]
Yes that would be correct order
On Aug 2, 2017, at 9:38 PM, tonglin <notifications@github.com<mailto:notifications@github.com>> wrote:


Recently I want to build the whole ROCm from source code, since there are so many repos and no clear steps, it's difficult for me to decide the right order to build the whole project. Here is my opinion about the order as follows, each represents one repo in ROCm, please tell me if it's right ? @gstoner<https://github.com/gstoner>

  1.  ROCK-Kernel-Driver
  2.  ROCT-Thunk-Interface
  3.  ROCR-Runtime
  4.  ROCm-Device-Libs
  5.  compiler-runtime
  6.  HCC
  7.  HIP
  8.  ROC-smi
  9.  ATMI

**Comment by lintcoder** [comment]
thanks, I want to build it on my ubunu16.04-arm64 server, when I run "make rock-rel_defconfig" following the  readme of ROCK-Kernel-Driver,  errors like "can't find rock-rel_defconfig" occur and the file .config can't be generated, while on x86_64 it worked,  should I replace the command with "make defconfig" ?

**Comment by lintcoder** [comment]
I replace "make rock-rel_defconfig" with "make defconfig" and make && make install, but the new kernel can't be loaded successfully and kernel file names like vmlinuz-4.9.0-00001-gfbf6230-dirty, what should I do ?  @gstoner
