### ISSUE TITLE
ROCm Kernel 4k resolution problem

### ISSUE THREAD

**Issue by reger-men** [RadeonOpenCompute/ROCm#227]
Hey everybody,

I installed new Ubuntu 16.04 on my PC. Then i followed the installation instruction as documented here: [ROCm](https://rocm.github.io/ROCmInstall.html).

![screenshot from 2017-10-16 18-32-28](https://user-images.githubusercontent.com/8779942/31627389-761f2088-b2ad-11e7-9182-944a621f918c.png)

After pc restart, I cannot select high resolution. (3840x2160)
![screenshot from 2017-10-16 18-31-06](https://user-images.githubusercontent.com/8779942/31627380-6d0ece94-b2ad-11e7-8c52-365117ca4674.png)

**OS:   Ubuntu 16.04
GPU: WX 7100**

Any idea?

**Comment by gstoner** [comment]
This is a mesa/amdgpu problem

**Comment by reger-men** [comment]
@gstoner I have no amdgpu-pro driver installed.

**Comment by jamilbk** [comment]
@reger-men The amdgpu and amdgpu-pro drivers are different. I use the amdgpu drivers from [this repository](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) to get everything working for me, but I'm on Vega FE.

**Comment by gstoner** [comment]
ROCm Userland compute components sit on amdgpu Linux driver.    The amdgpu Linux driver supports all of the X11/OpenGL, display logic. you can look at here   https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/tree/master/drivers/gpu/drm/amd 

If the issue is in the MesaGL and X11 userland components are part of your distribution, we do not distribute these.      ROCm really is only about GPU Computing solution.   We notify the Linux driver team your having an issue

**Comment by gstoner** [comment]
Here is good article on what going on in AMDGPU from Display perspective  https://www.phoronix.com/scan.php?page=news_item&px=AMD-Open-FreeSync-Planning 

https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-DC-Cleaning-Pre-4.15

**Comment by reger-men** [comment]
I installed ampgpu-pro 17.30, the 4k resolution is supported on `kernel 4.10` but not on ROCm `kernel 4.11`. That mean the ROCm drivers doesn't support 4k, is that right?
