### ISSUE TITLE
Broken multi-version install instructions

### ISSUE THREAD

**Issue by cgmb** [RadeonOpenCompute/ROCm#2401]
[The commands given to install multiple repositories](https://rocm.docs.amd.com/en/docs-5.5.1/deploy/linux/installer/install.html#add-required-repositories) are wrong:

```bash
for ver in 5.3.3 5.4.3; do
echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/rocm-keyring.gpg] https://repo.radeon.com/rocm/apt/$ver focal main" | sudo tee /etc/apt/sources.list.d/rocm.list
done
```
Each call to `echo <...> | sudo tee /etc/apt/sources.list.d/rocm.list` will truncate the file, so only the last version specified will be included in `rocm.list`.

**Comment by rtccreator** [comment]
$ver does never work the way it should.

The list is being truncated due to the given syntax. There is not `--append` flag after the `sudo tee` command. 

Do:
`echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/rocm-keyring.gpg] https://repo.radeon.com/rocm/apt/$ver focal main" | sudo tee **--append** /etc/apt/sources.list.d/rocm.list` with both of your versions pasted instead of `$ver`.

**Comment by Naraenda** [comment]
```sh
for ver in 5.3.3 5.4.3; do
echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/rocm-keyring.gpg] https://repo.radeon.com/rocm/apt/$ver focal main" | sudo tee --append foo
done
```

Gives the following when running `cat foo`
```
deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/rocm-keyring.gpg] https://repo.radeon.com/rocm/apt/5.3.3 focal main
deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/rocm-keyring.gpg] https://repo.radeon.com/rocm/apt/5.4.3 focal main
```

I'll update the install instructions to include `--append`
