### ISSUE TITLE
OpenCL:  kernels fail to run with error

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#253]
Memory access fault by GPU node-1 on address 0x916dd3000. Reason: Page not present or supervisor privilege.

I have two sequences of kernels,  the first sequence works fine, and the second gives this error.

I am running the latest package of ROCm. Hardware is an RX 470 on Asus Z170-K mobo.

**Comment by preda** [comment]
The first suspect is a genuine illegal memory access in your kernel. Can you post the source of the kernels, or a repro case? Or, why do you think it's something else?

**Comment by boxerab** [comment]
Thanks. I think it is a compiler bug. I reduced the kernel to a minimal case, and the error could be turned on or off with small changes to the code.  If it is not fixed in 1.7, I will put together a reproducer.

**Comment by boxerab** [comment]
Still broken with 1.7

**Comment by boxerab** [comment]
I have submitted a reproducer for this one.

**Comment by arsenm** [comment]
The code here seems to be trying to rely on the order of evaluation of the select function to do avoid an out of bounds access. Since select is a function call, all of the arguments are evaluated before the function. Additionally the order of evaluation of arguments to a function is undefined in C. In any case, the select can't be used to avoid the out of bounds access. If you rewrite this with if/then or the ternary operator which do have short circuiting behavior it should do what is expected.

**Comment by preda** [comment]
Where can one see "the code here"? (the reproducer)

**Comment by jlgreathouse** [comment]
@preda: @boxerab submitted a reproducer to AMD. I don't think we can share it on GitHub without his permission.

That said, @boxerab, if you would like, I can send you an updated copy of your reproducer that uses ternary (a ? b : c) statements in the kernel instead of select(c, b, a) statements. It prevents the crashes, as suggested by arsenm.

**Comment by preda** [comment]
No, that's fine. I understand that if the code has some reason for confidentiality, it should not be public here, that's fine.

It also sounds that you nailed the cause.
