### ISSUE TITLE
How to access AMD GPU with PyTorch

### ISSUE THREAD

**Issue by Aditya-Scalers** [RadeonOpenCompute/ROCm#2588]
Using PyTorch we are able to access AMD GPU by specifying device as 'cuda'.
Is this the recommended way to access AMD GPU through PyTorch ROCM?
What about 'hip' as a parameter for device?

```
from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained('gpt2', device_map="auto")
model = GPT2LMHeadModel.from_pretrained('gpt2', device_map="auto")
prompt = "What is Quantum Computing?"

encoded_input = tokenizer(prompt, return_tensors='pt')
encoded_input = encoded_input.to('cuda')

output = model.generate(**encoded_input, max_length=100)
print(tokenizer.decode(output[0], skip_special_tokens = True))
```

**Comment by danielzgtg** [comment]
> Is this the recommended way to access AMD GPU through PyTorch ROCM?

Yes, that is the recommended way, which I use, according to https://rocm.docs.amd.com/en/latest/how_to/pytorch_install/pytorch_install.html

> What about 'hip' as a parameter for device?

HIP aims to be compatible with CUDA. Many PyTorch projects only care about CUDA, and we are lucky that we can just install the ROCm version of PyTorch and it will still work with 'cuda' as a parameter. We don't want a 'hip' parameter because that would just make us AMD users get cut off from a big chunk of the ecosystem.

**Comment by Aditya-Scalers** [comment]
Thanks @danielzgtg, @jithunnair-amd for your response.
