### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by dmayle** [RadeonOpenCompute/ROCm#262]
Is there a timeline for RocM on MacOS?

**Comment by smithakihide** [comment]
I think there is no.
ROCm is based on customized linux kernel. so there is no compatibility with Unix kernel.

**Comment by gstoner** [comment]
Right now we need a way to port the ROCm tools to the Mac, which means exposed driver API and also LLVM IR interface,  AIR could be the path to get our compiler to work, but better would be the support of our standardized loader interface so we could also support Assembly.  This would be dependent on Apple tools team for the latter.

**Comment by oscarbg** [comment]
+1

Would be nice to expose ROCM i.e. improved compute on Macos right now OpenCL 1.2 for too many years while Nvidia supports CUDA..
seems Nvidia supports CUDA (even lastests features like "unified mem").. it just keeps releasing new CUDA releases and seems it works without Apple involvement.. couldn't AMD do the same with some ROCM.kext kernel driver extension similar to CUDA.kext?
just asking, no pressure..

**Comment by hery** [comment]
Hola! Just double-checking things here. Is it possible at all to get ROCm working for a Docker container running on macOS? Or can the ROC kernel not work that way?

**Comment by lambdaupb** [comment]
@hery Docker on macOS is run in a virtual machine. Since the radeon GPUs used in macs are used by the main OS and Hypervisor.framework does not support PCIe passthrough, Docker probably does not change the situation.

**Comment by leedrake5** [comment]
Just wanted to leave a vote here for a Mac version. Thanks for your efforts to make AMD GPUs work for deep learning.

**Comment by MatthewWaller** [comment]
Hello! I would like to throw in my request for a Mac version as well!

**Comment by leedrake5** [comment]
If you've come to this page looking for a Mac version, just keep commenting and leaving a vote. Don't know if it will change anything, but at least the developers will have a sense that demand is real. Though I also think Apple needs to step up and dedicate resources if they are going to stick with AMD.

**Comment by gentlesystems** [comment]
I've been watching this issue for a while.  Now I'm wondering if there's anything we can do to help make this happen.  The kernel code is more extensive than I would have expected.

**Comment by allenfrostline** [comment]
Still no progress? I thought it'd be an urgent issue and solved at least months ago...

**Comment by hery** [comment]
I ended up getting an Nvidia GPU. I feel like even if AMD makes decent GPU, the software stack is just so far behind.

**Comment by nehbit** [comment]
Yet another request for Mac OS. It doesn't have to be native, if you guys can get it to work in such a way that I can run it in a VirtualBox Linux VM, that would be just fine, too.

**Comment by timatrader** [comment]
It is simply a sin not to make support on mac os.

**Comment by Arthur77Wang** [comment]
Please do something for mac os support. Don't think it's such a complex staff to cover UNIX as LINUX support finished.

**Comment by mgbvox** [comment]
One more request for Mac OS Support. Please. How is this not a chief commercial concern?

**Comment by farleylai** [comment]
Apple is embracing AMD GPUs. The lack of support for macOS would be a pity. Two years are long enough for PyTorch to grow mature towards production. Though compilation from source is required for PyTorch to support nvidia GPUs on macOS, it's definitely working. So what's actually going on with ROCm?

**Comment by aleh-null** [comment]
Really surprised that it is like this. Plz do something, support Mac.

**Comment by bkozik** [comment]
+1 to macOS support, especially because Nvidia can't even work with Mojave.

**Comment by marcjones-io** [comment]
Hi 👋🏽 +1 over here on the MacOs support. Would be dreamy to accomplish all the tasks on one machine.

**Comment by plattenschieber** [comment]
Same here 👋

**Comment by iseanstevens** [comment]
Same here - I upgraded to a new MacBook pro with a vega56 as an eGPU and it's great but I'd love to be able to proudly exclaim how awesome it is by making some kick ass art-robots which currently are going to use an nVidia box.

**Comment by Degerz** [comment]
Why is this issue still even open ? It's Apple's full responsibility to maintain their compute stack so the people in this issue need to contact Apple instead to get a meaningful response from them ... 

For any of you guys that are interested in machine learning, why not ask for a single source C++ compute API like CUDA, HCC, SYCL from Apple because their Metal API is total junk ?

**Comment by gentlesystems** [comment]
The recent response from Degerz is unhelpful, and, in fact, highlights the disparity between the support from Nvidia and AMD.  Nvidia’s Cuda has taken over the industry and driven much of this kind of work away from AMD products, even where good hardware and APIs are available from AMD and competitors.  Nvidia continues to supply drivers for their video cards on Mac, as well as Cuda and OpenCL stacks, despite a lack of support and cooperation from Apple.  Meanwhile, Apples supplies AMD drivers and puts AMD cards in all of their products, but drivers and support from AMD themselves is starkly missing.

I realize that this Issue is unlikely to be resolved with anything other than a "won't fix" because ROCm so depends so much on its custom linux kernel, and Mac support would require a new effort to integrate with Mac.  However, Nvidia has already done this type of work and more.  Nvidia products are the biggest reason this project will fail or succeed, as they continually drive the parallel compute industry.  Apple is just a platform.  Negativity toward them or their APIs isn't very productive.

**Comment by Degerz** [comment]
> The recent response from Degerz is unhelpful, and, in fact, highlights the disparity between the support from Nvidia and AMD.

> Nvidia products are the biggest reason this project will fail or succeed, as they continually drive the parallel compute industry. Apple is just a platform. Negativity toward them or their APIs isn't very productive.

No, what's unhelpful are posts like yours in being complacent on accepting mediocrity from Apple and you can kiss goodbye to CUDA support on macOS starting from macOS Mojave so it's high time that you along with the others start holding Apple responsible for their subpar compute stack! 

It's exactly as you said, Apple are the ones who provide the drivers so they better damn well provide drivers adequate for machine learning or other high-end compute applications ... 

Demanding that AMD support a platform that they have no control whatsoever is not at all productive in any form and all the work that Nvidia has tried to bypass the macOS kernel has already been dropped. The fundamental issue with Apple's Metal API is that it's **_NOT_ single source** like CUDA or HIP but despite that design flaw AMD will gladly use Metal for some of their projects, however it'll never become a viable option for machine learning. It's amazing that you're quick to point out AMD's failings but will ignore Apple making the very same mistake twice already once with OpenCL and another with Metal both of which are designed as separate source ... 

How do you expect the community to cope with a useless tool ?

**Comment by hmmmph** [comment]
Contrary to the complete rubbish the previous commenter spewed, `Apple` nor the Metal API is to blame (in case you didn't know, [OS X is opensource](https://opensource.apple.com)). 

There are many other projects that were once exclusive to `CUDA` that support `OpenCL`/`AMD` GPU's on macOS now (eg. hashcat). The lack of a macOS compatible tensorflow-rocm is more likely simply not where the developer's priorities are atm. `AMD` has a [portal](https://amd-osx.com) and [community](https://forum.amd-osx.com) exclusively dedicated to `OS X`, maybe put in a request over there perhaps — that's why it exists.

**Comment by Degerz** [comment]
> AMD has a portal and community exclusively dedicated to OS X, maybe put in a request over there perhaps — that's why it exists.

"**AMD OS X is in no way affiliated with © Advanced Micro Devices Inc**, © Apple Inc or any of their subsidiaries. **All opinions and reviews are our own.**"

This is why no one takes the Apple community seriously ... 

> Apple nor the Metal API is to blame (in case you didn't know, OS X is opensource).

Too bad they didn't open source where it actually mattered which was their graphics/compute stack and Metal API is indeed to blame since it's not single source ... 

> There are many other projects that were once exclusive to CUDA that support OpenCL/AMD GPU's on macOS now (eg. hashcat). 

And their still exclusive to CUDA to this very day! Consider OpenCL as effectively deprecated with no future. There's no future in compute either on Windows or macOS ...

> The lack of a macOS compatible tensorflow-rocm is more likely simply not where the developer's priorities are atm.

You must be very naive behind the reasons as to why ROCm exists in the first place ...

**Comment by gbrow004** [comment]
Another +1 for MacOS support, even if we have to compile from source (I'm looking at you PyTorch with GPU support for MacOS!).

**Comment by maddyscientist** [comment]
With the recent announcement of the new Mac Pros with up to 4x Vega 7s in them, which would be a dream ROCm workstation, have there been any plans made yet to address ROCm on Mac yet?

**Comment by Degerz** [comment]
@maddyscientist Don't ask AMD ? Go ask Apple instead and ask them when they're going to support a single-source programming model ? 

If your interest like everyone else in here is in machine learning frameworks such as Tensorflow, PyTorch, etc then ROCm only works because it's APIs support template kernels/shaders ... 

No matter how many people ask AMD or plead for them to bring over ROCm to MacOS, it'll never happen because Apple only wants to support inferior programming models ...

**Comment by maddyscientist** [comment]
@Degerz so how come CUDA works on Mac but not ROCm?

**Comment by Degerz** [comment]
@maddyscientist Not anymore it doesn't starting from macOS version 10.14. There's going to be no more CUDA support starting on Mojave and subsequently no CUDA as well on Catalina ... 

Again, no single-source programming model means no advanced machine learning frameworks like Tensorflow or PyTorch ... 

You can tell there's an echochamber in here from people not willing to admit that what Apple are doing with their Metal API is total rubbish. They should give Metal the ability to do templated kernels/shaders or they can get get lost ... 

Metal = pile of hot junk :wink:

**Comment by bofeizhu** [comment]
Metal’s API is Objective-C based… so it’s kinda rubbishy. They should have gone all in with Swift and bridge with Swift for Tensorflow. But I guess nobody could predict the future.

**Comment by ThoreauHenry** [comment]
On the practical/linux side of things, it's either integrated into the newest kernel or inserted as a dkms module into the kernel at runtime.  If Apple's Mach kernel disallows that, it will be impossible to run.  OS X is not open source.  The freebsd kernel they swiped is closes source.  You need Apple's keys and/or permission to access it.

If Apple wanted ROCm implemented, it could be done in a month with the code here that is freely available.  But they don't want to.  From their recent announcements they are going to reinvent the wheel with metal.  And I understand why, because it must integrate with their kernel, which is in fact a vertical/closed package.  So they literally have to do it themselves unless NDA's/permission are granted to an outside vendor, as was done with Nvidia(for a short time).  I'm sure Apple will be releasing some kind of compute layer shortly with metal.  I just doubt it'll be called ROCm.

**Comment by Degerz** [comment]
They won't because Apple only intends for Metal to be a gfx API and even then it's missing tons of features. Literally, every time some developer uses it beyond games it fails pretty hard and miserably at that ... 

From [years](https://forums.developer.apple.com/thread/8359) on since it's release, an AMD employee has made the [same](https://github.com/ROCm-Developer-Tools/HIP/issues/150#issuecomment-321272082) complaint. There are currently ZERO and EXACTLY ZERO ways to be able to do CUDA-style templates on Apple systems currently since Metal is a dumpster fire of a compute API. If Metal actually had the ability to execute CUDA-style templates then having CUDA or ROCm on their platforms would become redundant and any serious professionals with Apple cash wouldn't care but this is not the case so here we are where we have people who guilty of putting up with an inferior programming model from Apple ... 

Metal is just another abomination to ML framework specialists and unless somebody [demands](https://forums.developer.apple.com/thread/118774) that Apple support a single-source programming model like CUDA then nothing will change ...

**Comment by paradox56** [comment]
Currently, one solution to do deep learning on a Mac with external GPU is to use PlaidML, which supports Keras. I have successfully tested it with an external RX580 GPU. 

it might be also be possible to add support to TensorFlow 2.0, as shown in the comment: [Plaidml_issue_281](https://github.com/plaidml/plaidml/issues/281#issuecomment-478260583). 

That being said, it will be exciting if ROCm can support Mac OS as well, especially after the release of Apple cheese grater.

**Comment by lericson** [comment]
+1 for AMD GPGPU support, I don't really care if it's ROCm or HIP. Just let me write GPU-accelerated programs like CUDA does. This is a problem with lack of vision from both Apple with its shader file approach in the Metal API, and a from AMD with having ROCm be tied to Linux.

**Comment by lericson** [comment]
@paradox56 The acceleration in PlaidML works by reverting to graphics-based approaches from yesteryear. It is really rather a sad testament that it is easier to regress to previous techniques than to get AMD/Apple on the same page in this.

**Comment by fzzr-** [comment]
I just found 

> A MTLComputePipelineState object represents a compute processing pipeline. Unlike a graphics rendering pipeline, you can create a MTLComputePipelineState object with a single kernel function, without using a pipeline descriptor.

https://developer.apple.com/documentation/metal/hello_compute

**Comment by lericson** [comment]
It is not single-source, and the API is ridiculously complex to call a single function, sadly. 

- Ludvig

**Comment by leedrake5** [comment]
> @paradox56 The acceleration in PlaidML works by reverting to graphics-based approaches from yesteryear. It is really rather a sad testament that it is easier to regress to previous techniques than to get AMD/Apple on the same page in this.

This is true, but having worked with CUDA on a Linux system, the plaidml framework has been much more stable and easier to use. It regulates itself far better with available RAM, as one example.

**Comment by Aeroxander** [comment]
The TVM deep learning compiler stack should also have Metal support, PlaidML doesn't have support for every type of operator yet (or at least not for my more advanced model, normal ones should work)

**Comment by kenthinson** [comment]
Everyone should ask Apple to implement the drivers changes to make ROCm possible on osx. Send them feedback. I will be doing so also.

https://www.apple.com/feedback/macos.html

**Comment by songololo** [comment]
@kenthinson that or find a journalist to investigate and publish whether Apple develops their ML using non-apple workflows...!

**Comment by Degerz** [comment]
It's finally official, Nvidia will drop CUDA support after release 10.2 and no amount of shouting or screaming at AMD will reverse this decision since they were never at fault to begin with like some people here seem to have implied ... :sunglasses:

Their trash Metal API will have to meet these 3 demands to be even considered again or else ... 

1. Single-source programming model 
2. Support for templated kernels and other common C++ features found in CUDA/HIP
3. Support for an offline compilation model

Until these demands are met by Apple their Metal API will be straight garbage. Even Intel with their oneAPI compute stack and their DPC++ API is a better idea than Metal which shows just how pathetic Apple's support has been thus far for this community ...

**Comment by leedrake5** [comment]
Looks like [PlaidML](https://github.com/plaidml/plaidml) is the only viable option moving forward

**Comment by mirh** [comment]
Plaid is a "program". You'll mean opencl as the equivalent api to rocm, for eventually talking with the gpu.
But that's already been deprecated last year, bets are taken on when it will be removed too.

**Comment by leedrake5** [comment]
PlaidML works with metal too. So I don’t anticipate any problems. Because it is a program, it is a little more robust to Apple’s baffling decisions. I don’t know how well it will Leah with Keras now that it is integrated within tensorflow in v2.

**Comment by bofeizhu** [comment]
@Degerz Will MLIR make any difference in the future?

**Comment by Degerz** [comment]
@bofeizhu Unfortunately, I don't think MLIR is going to help with the situation on macOS all that much. It looks to be an even higher level IR than SPIR-V! SPIR-V compute shaders in Vulkan as it is have too many limitations for targeting advanced machine learning frameworks like Tensorflow or PyTorch so MLIR targeting SPIR-V won't end well IMO ... 

My main motivation behind demanding an offline compilation model for Metal (or any other API really) is because nobody wants to deal with the weaknesses of high-level abstractions such as SPIR-V or MSL (Metal Shading Language). An offline compilation model would offer us more powerful programming features to enable more complex frameworks like machine learning and more powerful  lower level optimizations ... 

Currently today, shading languages/bytecode aren't very powerful abstractions of the hardware we use. CUDA proves that having a less portable standard is a more powerful tool and the industry is slowly starting to acknowledge this in the current ecosystem ... 

CUDA kernel language -> PTX ISA -> SASS (Nvidia)
DPC++ kernel language -> GEN ISA (Intel)
HIP kernel language -> GCN ISA (AMD) 

Apple like with the above standards should embrace CUDA's programming/compilation model rather than Direct3D or Vulkan's programming/compilation model with the Metal API if they want to have any chance of success with complex machine learning frameworks. MSL is unacceptable as it is but if Apple doesn't want an offline compilation model for portability reasons then they should at least give us something lower level like a virtual ISA such as PTX because things can't keep going on like this ...

**Comment by bofeizhu** [comment]
@Degerz Correct me if I’m wrong, but I think MLIR is supposed to be working with Swift for Tensorflow. And we can use Swift to write every layer of the deep learning stack and compile them directly to hardware.

**Comment by Degerz** [comment]
@bofeizhu Think of it like this ... 

MLIR uses a source language as an input (such as Swift as you mentioned) as the **front-end** for the intermediate representation and then compiles it into the target back-end intermediate representation or native ISA (like PTX or GCN ISA) ... (following example)

Swift source language -> (source-to-IR compiler) -> MLIR -> (IR-to-IR/ISA compiler) -> PTX ISA
Input source language -> (front-end compiler) -> MLIR -> (back-end compiler) -> hardware IR/ISA

MLIR is just simply another layer in the compilation process. IMO the biggest hurdle to Tensorflow support on macOS/Metal isn't going to be the source language or the higher level IR but it's going to be the back-end IR/ISA ... 

Right now we can't just simply use the Metal Shading Language to support the full featured Tensorflow framework because it doesn't have enough features. At best it's only good enough for Tensorflow Lite and it's the same story with SPIR-V ... 

We need a lower level target from Apple to be able to have Tensorflow use the Metal API. If we had access to some sort of virtual ISA like PTX or even a native ISA like GCN bytecode in Metal API then we could just start porting existing CUDA/HIP kernels by writing custom hand optimized Metal shaders with assembly code instead of only using the high level MSL source which is not nearly as powerful or featured compared to the assembly language ... 

The biggest gripe with the Metal API is that it's not nearly low level enough compared to CUDA in which you can write kernels using Nvidia's assembly language for their GPUs known as PTX or with HIP in AMD's case you can write HIP kernels using GCN assembly! Where is Metal's equivalent to PTX or GCN ISA in Apple's case ?

**Comment by ayushnvijay** [comment]
Has anyone tried using Parallels desktop with Ubuntu to make this work? Or nGraph to use tensorflow on AMD Gpu?

**Comment by mk2016a** [comment]
It is not a problem with apple.
Apple now has its Creative ML which is easy for app developer to use.
Even the cuda support old Mac system.
How could AMD be so much worse ?
I think Apple should not use AMD graphics card at all.
Price of a Mac is far more enough for them to Nvidia's best graphics cards.
Because of the lower cost of its product, now we can only use stupid AMD's graphic card with almost no support at all.

Apple should not use amd.
As long as apple using amd's graphics card, we will never buy any apple computer again.
Things like this, really stupid and Apple is no longer the old Apple any more.

**Comment by Nevensky** [comment]
vote up for adding mac support

**Comment by zhiyuanzhai** [comment]
+1. We want Radeon Open Compute for Mac!
Now I have to install an Arch Linux system on my MacBook Pro, which means a huge amount of extra work to do.

**Comment by jjbeto** [comment]
+1

**Comment by jjbeto** [comment]
vote up for adding mac support

**Comment by ugahugo** [comment]
It will never happen. The original team didn't introduce nor HAL, nor other critical components in order to introduce new OS support at any point in the future.

**Comment by MirrMurr** [comment]
Still holding up and staying in the line for Mac support!

I'm also interested in whether it has more chance of this Mac support happening, or rather buy an Nvidia eGPU. What is your advice? Any comment is welcome!

(I'm a computer scientist student studying Deep Learning, using MBP 15", yet no use of the Radeon Pro inside.....)

**Comment by ugahugo** [comment]
> Still holding up and staying in the line for Mac support!
> 
> I'm also interested in whether it has more chance of this Mac support happening, or rather buy an Nvidia eGPU. What is your advice? Any comment is welcome!
> 
> (I'm a computer scientist student studying Deep Learning, using MBP 15", yet no use of the Radeon Pro inside.....)

Nvidia drivers were canceled for past major MAC OS updates, so no Nvidia eGPU support for you unless you roll back to the older versions (which is a big pain in the ass considering other apps support for old MAC OS versions). 

Welcome to hell.

**Comment by MirrMurr** [comment]
> > Still holding up and staying in the line for Mac support!
> > I'm also interested in whether it has more chance of this Mac support happening, or rather buy an Nvidia eGPU. What is your advice? Any comment is welcome!
> > (I'm a computer scientist student studying Deep Learning, using MBP 15", yet no use of the Radeon Pro inside.....)
> 
> Nvidia drivers support was canceled for past major MAC OS updates, so no Nvidia eGPU support for you, unless you roll back your Apple product to the older OS versions (which is a big pain in the ass considering other apps support for old MAC OS versions).
> 
> Welcome to hell.

Thank you for replying! 

Wow, this is really an eye opening inconvenience.. I guess stick to Google Colab and pray for PlaidML or Apple or some god. Until then, maybe spin up an Ubuntu machine.

**Comment by ChristianLagares** [comment]
Yet another vote for a MacOS port. This would enable not only ML workloads to be accelerated, but also many other HPC-related workloads to _at least_ compile natively on MacOS. Apple has recently shown its commit for Radeon with the introduction of the 5600M with HBM2. I do understand a significant amount of work would be required, but the payoff of enabling a large amount of workloads seems to outweigh the initial effort.

**Comment by Gerzer** [comment]
Please do port ROCm to Metal on macOS! There's a huge demand for that.

**Comment by mk2016a** [comment]
Forget it. No company would like to corperate with ATI. That is why they went bankrupt.

**Comment by Nevensky** [comment]
I wish to throw my ball in this game as well, please port the Rocm to MacOS / Metal.

**Comment by saharqadan** [comment]
please do port RocM on MacOS

**Comment by greenstick** [comment]
Still dreaming about this by night and living the nightmare of no MacOS support by day.

**Comment by Filco306** [comment]
Would a reasonable workaround be to partition one's disk and install Ubuntu? Would that enable the use of one's graphic's card?

**Comment by gbrow004** [comment]
> Would a reasonable workaround be to partition one's disk and install Ubuntu? Would that enable the use of one's graphic's card?

Yes, but installing Ubuntu on Macs that have the T2 security chip (2018 and later) can be troublesome. You can try my guide to start out:
https://gist.github.com/gbrow004/096f845c8fe8d03ef9009fbb87b781a4

**Comment by Filco306** [comment]
Thank you @gbrow004 , I will check it out!

**Comment by pkla** [comment]
Leaving my vote. With AMD being the sole third party dedicated GPU option on MacOS, ROCm support seems like a no-brainer. Please make this happen!

**Comment by ugahugo** [comment]
@gstoner, 

Do you see this? Hundreds of people voted for make damn Windows / Mac OS X support, not useless for Linux. This is what should be done from the very beginning!

**Comment by egorgam** [comment]
How I understand a situation, it must be some core patches for use RoCM on linux (what is unreal wit proprietary Darwin core) but MacOS implementation can't passtrough PCI devices (as discrete GPU). So where is any possible way for AMD developers to resolve a problem?

**Comment by ChristianLagares** [comment]
And you are right, @egorgam . However, many other API's have successfully been ported to run atop Metal. For instance, MoltenGL provides OpenGL ES 2.0 over Metal. Metal already provides a low-latency, API that could be targeted. I'm fairly confident that a large portion of the ROCm Core could be ported to run over Metal which would provide a Native platform. Not to mention, AMD would incentivize developer investment. 

I have to disagree with @ugahugo. AMD did the right move by bringing Linux into the play. For ROCm to succeed, they needed to appeal the HPC market, but their greatest mistake was to relinquish ROCm to being a niche development platform more or less exclusive to Linux. For instance, CUDA's greatest success comes from targeting every Nvidia GPU. AMD has a massive consumer and prosumer marker that they are not aggressively targeting by not porting ROCm. I do believe that even the development effort required for ROCm over Metal would render their codebase much more robust and mature enough to target newer platforms. They already have HIP. Why not add Metal as a backend? I have a Radeon Pro 5600M that I can only target through Metal (which is painful to target from C++ or Python) or OpenCL (relegated to 1.0). Apple recently published TensorFlow running on ML Compute. Why would AMD lose a marketing opportunity to bring ROCm over Metal which could potentially pave the way to ROCm over DirectCompute. This would enable fully portable AMD GPU compute shaders.

**Comment by egorgam** [comment]
@ChristianLagares wow! https://github.com/apple/tensorflow_macos/issues/7#issuecomment-730073221 look like it works with radeon pro)

**Comment by ugahugo** [comment]
> I have to disagree with @ugahugo. AMD did the right move by bringing Linux into the play. For ROCm to succeed, they needed to appeal the HPC market, but their greatest mistake was to relinquish ROCm to being a niche development platform more or less exclusive to Linux.

>I have to disagree

>but their greatest mistake was to relinquish ROCm to being a niche development platform more or less exclusive to Linux

nuff said

**Comment by zhiyuanzhai** [comment]
@ugahugo It's clear that ROCm is aimed at High Performance Computing, which is mostly applied on clusters, servers, supercomputers or workstations, rather than a desktop or laptop PC. In those systems, Linux is undoubtedly the most popular OS, thus Linux has to be focused on. Actually the most recommended OS for CUDA from NVidia is also Ubuntu Linux. It makes sense if AMD would like to apply ROCm to Linux first.

Now we are just waiting to see if AMD has the plan to bring ROCm to other OSs like macOS or Windows after ROCm is mature enough on Linux.

**Comment by ugahugo** [comment]
Do you know that with modern GPU there is no such thing as a supercomputer market? That modern laptops, gaming laptops are for more advanced that you have in your mind and calling as "workstations"? I mean, the addressable market is huge, far bigger than the traditional supercomputer market you mentioned. 

Watching the Radeon unit fan zone explaining why the Radeon unit shot themselves into the leg by targeting a tiny market looks really bad! 

Why Nvidia did everything perfectly? Once and everything, and for everyone? What's the purpose of limiting something? What's the purpose of avoiding the C++ for Windows and Mac OS X in 2020? I see the only reason is bad management and lack of skills in code development, and I am not sorry for that because it's not my problem but AMD's... 

I didn't understand two things in this topic and others in ROCm: 

1. Why people are trying to protect AMD's when they obviously failed alone (I didn't help them to fail, nor did any of you)

2. And why AMD continuously closing all the issues related to other OS support, providing 0 amount of information on plans and progress while the community just literally demanded this by hundreds of votes?! I just can't stand that behavior!

I see the behavior for such a huge corporation as AMD / Radeon just unacceptable. They chose to mute these problems, ignore the elephants in the room, they chose to avoid the problem. 

Do they think this problem will be gone if they just ignore it? I don't have anything to say to them

**Comment by mirh** [comment]
> What's the purpose of limiting something?

Idk, if you really cared about arbitrary limitations you shouldn't be using apple products I guess. 
Anyway, just for the records, with the release of ROCclr I believe HIP/rocm should be very near (if it isn't already?) to running on Windows.

**Comment by ROCmSupport** [comment]
Currently we are not supporting MacOS with ROCm.
We will share an update once we have plans to support in future.
Thank you.

**Comment by leedrake5** [comment]
Hi all,

Good news, Apple has released a version of tensorflow that can use AMD GPUs. See it [here](https://github.com/apple/tensorflow_macos).

**Comment by ugahugo** [comment]
> Hi all,
> 
> Good news, Apple has released a version of tensorflow that can use AMD GPUs. See it [here](https://github.com/apple/tensorflow_macos).

What is the point to post this here? It's not related to the ROCm. More of that, having the TensorFlow library compiled for Mac OS X isn't the big deal. Also, the GPU acceleration for the case of M1 will be just really low comparing with PC

**Comment by martinezhermes** [comment]
> > Hi all,
> > Good news, Apple has released a version of tensorflow that can use AMD GPUs. See it [here](https://github.com/apple/tensorflow_macos).
> 
> What is the point to post this here? It's not related to the ROCm. More of that, having the TensorFlow library compiled for Mac OS X isn't the big deal. Also, the GPU acceleration for the case of M1 will be just really low comparing with PC

I believe people that follow this issue here are looking for ways for using their AMD GPU for machine learning, what @leedrake5  has replied comes as the _only_ solution so far for this issue! yes, tensorflow_macos is not related to ROCm at all but it is in fact related to AMD GPU cards in Mac computers. I’ve been testing it for the past 3 weeks and the performance is getting there, it is almost as fast as my ROCm setup using linux (with the same Mac) for both training and inference. 

I also believe ROCm on macOS is never gonna happen. I suggest people to follow the tensorflow development and post issues over there, hopefully pytorch and other libs will follow through, otherwise using Xcode Swift and PythonKit is also an option for machine learning projects with Mac computers that have AMD dedicated GPUs.

**Comment by greenstick** [comment]
> > > Hi all,
> > > Good news, Apple has released a version of tensorflow that can use AMD GPUs. See it [here](https://github.com/apple/tensorflow_macos).
> > 
> > 
> > What is the point to post this here? It's not related to the ROCm. More of that, having the TensorFlow library compiled for Mac OS X isn't the big deal. Also, the GPU acceleration for the case of M1 will be just really low comparing with PC
> 
> I believe people that follow this issue here are looking for ways for using their AMD GPU for machine learning, what @leedrake5 has replied comes as the _only_ solution so far for this issue! yes, tensorflow_macos is not related to ROCm at all but it is in fact related to AMD GPU cards in Mac computers. I’ve been testing it for the past 3 weeks and the performance is getting there, it is almost as fast as my ROCm setup using linux (with the same Mac) for both training and inference.
> 
> I also believe ROCm on macOS is never gonna happen. I suggest people to follow the tensorflow development and post issues over there, hopefully pytorch and other libs will follow through, otherwise using Xcode Swift and PythonKit is also an option for machine learning projects with Mac computers that have AMD dedicated GPUs.

Sure, a lot (maybe even most) people are hoping for ROCm support on Mac so that they can use ML libraries, and in that respect the info provided by @leedrake5  is helpful. Let's be real, though –  tensorflow is _one library_ among _one use case_. Full ROCm support would allow developers to create their own libraries/applications that leverage their AMD GPU on their Mac – that's what I was after. I agree with you, ROCm for Mac will probably never happen, especially now that Apple's push towards SoCs with integrated GPUs on their laptop and desktop offerings (M1) is finally being rolled out in production, but your belief that people are following this issue because they're "looking for ways for using their AMD GPU for machine learning" is reductive. And even if that were the case, the idea that we should be satisfied now that tensorflow supports it (e.g. what about pytorch?) is wrongheaded. This is (...was *sigh*) bigger than a single library or use case; this was about supporting a platform.

**Comment by zhiyuanzhai** [comment]
In my perspective, Apple is unlikely to accept ROCm on Mac, for the same reason why Apple refused to support CUDA at the very beginning. It's not Apple's manner to rely on other manufacturers on such an important field as GPGPU.

It's becoming more and more clear that Apple is trying to push forward their own platform on GPU rendering and parallel computing, i.e., the Metal API.

**Comment by Crear12** [comment]
> 

With the promotion of Silicon platform, I think that this wish can never be realized.
