### ISSUE TITLE
ROCm-dkms and secure boot

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm#276]
Does secure boot need to be disabled for the new DKMS version of ROCm ?

**Comment by steemandlinux** [comment]
RTFM? https://wiki.archlinux.org/index.php/Secure_Boot

**Comment by boxerab** [comment]
Dear Random Internet Person,

My question was about secure boot **and DKMS**, of which your link makes no mention, so it hardly
qualifies as the fucking manual.  Your comment comes across as both arrogant and ignorant.

**Comment by boxerab** [comment]
anyways, I disabled secure boot on my system. Everything seems to be working fine.

**Comment by boxerab** [comment]
But, if it is _required_ to disable secure boot, this should be put in the docs somewhere.

**Comment by gstoner** [comment]
Arron, we look into this after the Christmas break.

**Comment by seesturm** [comment]
https://wiki.ubuntu.com/UEFI/SecureBoot/DKMS appears to provide a brief overview on the options of using DKMS together with SecureBoot. If I get it right it is not strictly required to disable secure boot with DKMS. Here are the options shown:

1. Sign the kernel module using a trusted key (probably requires interaction with mokutil, MOK stands for MachineOwnerKey). Maybe this does not happen automatically since something is missing from the AMD install scripts.
2. Disable secure boot in UEFI.
3. Disable secure boot in SHIM.

Note1: I don't have an UEFI PC myself so I cannot test anything. I intend to buy a new PC and am collecting information about restrictions due to UEFI.

**Comment by boxerab** [comment]
re-opening this as this seems to be an issue for a number of users
