### ISSUE TITLE
GDS access

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#308]
This is a feature request:

Please provide/document a way to use GDS, and a sample.

**Comment by gstoner** [comment]
This is something we have been looking in too.  It is still just preliminary research

**Comment by ob7** [comment]
What is GDS?

**Comment by preda** [comment]
Global Data Share. It is similar to LDS (Local Data Share), but global i.e. shared between all the workgroups. Could be a very fast solution for some particular situations, but it is not exposed by the API (such as OpenCL).
See
https://developer.amd.com/wp-content/resources/Vega_Shader_ISA_28July2017.pdf

**Comment by preda** [comment]
Any update on exposing GDS?

**Comment by jlgreathouse** [comment]
We're still internally exploring the best way to expose this feature through our languages and runtimes. I have a helper library built that I use internally to access this hardware mechanism, and I'm going to try to see if I can release that through the Experimental ROC repo. However, I'll note that my experimental mechanisms are extremely not-product-ready. For instance, the GDS space is not virtualized, so every process using a GPU on the entire system would be able to see (and modify!) what's written. Very not-safe for general use.

Stuff like virtualizing the GDS, handling "what happens when multiple processes all want the GDS?", making GDS space part of task switch space, and sharing GDS between compute and graphics are just part of what we're working through as we think about this feature.

**Comment by ROCmSupport** [comment]
Thanks @preda 
As its very old issue, and no updates for the last 2 years, this issue is going to be closed.
Request to open a new ticket, if you found any.
Thank you.
