### ISSUE TITLE
Is the Git version of LLVM fully compatible with ROCm?

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/ROCm#36]
Are all ROC-related changes merged into LLVM master? Is LLVM master compatible with ROCm 1.2? I have to use LLVM master due to a fixed bug. It seems to work, but I thought to ask.

**Comment by gstoner** [comment]
ROCm master is current source tree, there will be update with ROCm 1.3

greg
On Oct 4, 2016, at 7:51 AM, almson <notifications@github.com<mailto:notifications@github.com>> wrote:


Are all ROC-related changes merged into LLVM master? Is LLVM master compatible with ROCm 1.2? I have to use LLVM master due to a fixed bug. It seems to work, but I thought to ask.

**Comment by arodrigx7** [comment]
Hey almson,

Our team works close together with the LLVM master repos. Everything you need to run ROCm should be available in master as we upstream our changes fairly often and run some simple validation tests against the latest public ROCm stack.

Do take into account that LLVM master is not a stable branch though, so you may encounter some unexpected issues. Our devs that work on the llvm components frequent the LLVM mailing lists. So if you do encounter an issue when running this branch that would be a good first place to send feedback.
