### ISSUE TITLE
Can't install ROCm 1.8.1 with Ubuntu 16.04 LTS (Desktop version)

### ISSUE THREAD

**Issue by MoneroCrusher** [RadeonOpenCompute/ROCm#439]
Hi there,

I have followed every step in https://github.com/RadeonOpenCompute/ROCm and yet when I come to the step where I have to type "rocminfo" it returns "rocminfo: command not found". uname -r also doesn't look like it's a ROCm kernel.."4.13.0-45-generic".
Setup:
Intel Celeron G3930
RX 550 hooked up via a riser into the 16x slot.

amdgpu-pro 18.20 works perfectly. But I need the ROCm kernel. Any suggestions?

edit: also, it was a fresh install of Ubuntu 16.04 LTS, so no old ROCm kernels were present at any moment...
sudo dkms status returns
amdgpu, 1.8-151, 4.13.0-45-generic, x86_64: installed
and yes, I added user to video group
also, cl info outputs Number Of platforms 0

**Comment by jlgreathouse** [comment]
Is this an OEM-built system (e.g. from HP, Dell, etc.) or did you build it yourself? If the former, what model is it? If the latter, what motherboard are you using? What kind of PCIe riser is this? A passive connector, or are you trying to install the GPU through some kind of active lane-splitter?

Could you please include the outputs of the following commands?

- `lsmod | grep amdgpu`
- `lsmod | grep amdkfd`
- `groups`
- `lspci | grep VGA`
- `lspci -vvv`
- `lspci -tv`
- After a reboot: `dmesg | grep kfd`
- `/opt/rocm/bin/rocminfo`
- `/opt/rocm/opencl/bin/x86_64/clinfo`

Thank you.

**Comment by MoneroCrusher** [comment]
@Bengt How do I call it?
@jlgreathouse It's a self-built system with a TB250 BTC-PRO Biostar motherboard. It's a normal PCIe Riser used in usual cryptocurrency mining setups.
I will provide feedbacks of these commands this saturday. 
Thank you for the feedback.

**Comment by Bengt** [comment]
@MoneroCrusher you should be able to call it just like that from a terminal. Here is an example output from my current machine:

```
bengt@Bengt-TR4:~$ /opt/rocm/bin/rocminfo
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (number of timestamp)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******
[...]
```

**Comment by jlgreathouse** [comment]
Coming back to the original problem reported by @MoneroCrusher -- are you still planning to report the feedback from those commands?

**Comment by MoneroCrusher** [comment]
Upon further research I think that this CPU/Chipset only supports atomics on the x16 slot (not sure about this, just speculation from my side) and since Vega can run without atomics, that's the reason why it's showing up.

Here's the rocm_bandwidth_test with Vega 56 in a x1 PCIe slot (without atomics) and the Lexa Pro RX 550 in the x16 (presumably with atomics):
```
root@A12:/# /opt/rocm/bin/rocm_bandwidth_test/build/rocm_bandwidth_test
............
........

          RocmBandwidthTest Version: 1.0.0

          Device: 0,  Intel(R) Celeron(R) CPU G3930 @ 2.90GHz
          Device: 1,  Device 699f
          Device: 2,  Device 687f

          Device Access

          D/D       0         1         2

          0         1         1         1

          1         1         1         0

          2         1         0         1


          Device Numa Distance

          D/D       0         1         2

          0         0         N/A       N/A

          1         20        0         N/A

          2         20        N/A       0


          Unidirectional peak bandwidth GB/s

          D/D       0           1           2

          0         N/A         0.317793    0.439568

          1         0.342809    35.045983   N/A

          2         0.453472    N/A         169.844045


          Bdirectional peak bandwidth GB/s

          D/D       0           1           2

          0         N/A         0.530917    0.823345

          1         0.530163    N/A         N/A

          2         0.823482    N/A         N/A
```
```
root@A12:/# /opt/rocm/bin/rocm_bandwidth_test/build/rocm_bandwidth_test -v


          RocmBandwidthTest Version: 1.0.0

          Device: 0,  Intel(R) Celeron(R) CPU G3930 @ 2.90GHz
          Device: 1,  Device 699f
          Device: 2,  Device 687f

          Device Access

          D/D       0         1         2

          0         1         1         1

          1         1         1         0

          2         1         0         1


          Data Path Validation

          D/D       0           1           2

          0         N/A         FAIL        FAIL

          1         FAIL        PASS        N/A

          2         FAIL        N/A         PASS
```
```
root@A12:/# /opt/rocm/bin/rocm_bandwidth_test/build/rocm_bandwidth_test -t

          Device Index:                             0
            Device Type:                            CPU
              Allocatable Memory Size (KB):         3968024

          Device Index:                             1
            Device Type:                            GPU
              Allocatable Memory Size (KB):         2097152

          Device Index:                             2
            Device Type:                            GPU
              Allocatable Memory Size (KB):         8372224


          Device Access

          D/D       0         1         2

          0         1         1         1

          1         1         1         0

          2         1         0         1


          Device Numa Distance

          D/D       0         1         2

          0         0         N/A       N/A

          1         20        0         N/A

          2         20        N/A       0
```

I am looking to potentially transform my low-end GPU mining farm into a lightweight Deep Learning farm. Although as of now it's looking bad that is even possible with ROCm.
Now my question: If one were to "only" have numbers, nothing too complex as a dataset, would it make sense or would it be possible to run everything without atomics?

Or is there an alternative to use tensorflow without ROCm? I'm quite satisfied with the performance of AMDGPU Pro 16.60, I get 1/4 the performance of a Vega 56 mining cryptonight (both at max settings).

**Comment by MoneroCrusher** [comment]
Also: I can manually set each PCIe port to gen3 and boot/mine in that mode.

**Comment by jlgreathouse** [comment]
Hi @MoneroCrusher 

Sorry about the delay in responding to this. It's difficult for me to keep up on posts in closed issues, since they're "marked as read" as soon as I read the email and then I never see them again unless I make a concerted effort to look for closed issues that were recently updated.

You're right, we added Polaris 12 ("Lexa") support [in ROCm 2.0](https://github.com/RadeonOpenCompute/ROCm/blob/roc-2.0.0/README.md#adds-support-for-vega-7nm-polaris-12-gpus). However, since Polaris 12 is a gfx8 GPU, it still maintains [the same limitations as other gfx8 GPUs with respect to PCIe atomics](https://github.com/RadeonOpenCompute/ROCm/blob/roc-2.0.0/README.md#not-supported).

Thus, I suspect you are right that the reason you are unable to see your GPUs is because you do not have PCIe atomics support for your large number of 1x slots. This is probably because these slots sit behind a PCIe switch that, to reduce costs, [was not designed to route/forward atomic operations](https://rocm.github.io/hardware.html#supported-cpus).

It's not just a question of PCIe 3.0, 2.0, or 1.0. PCIe atomics are an extension to PCIe 3.0 that may not be supported by all CPUs and switches. It's possible to have a system where you have many slots running x1, and each of them properly sees PCIe atomics. However, this requires the PCIe switch being used to split the PCIe connection to be able to properly forward atomics. Most of the switches we have tested that are used in cost-conscious systems like mining rigs do not have this capability and thus the x1 slots cannot be used with gfx8 GPUs.

As discussed in detail in [my posts in this other issue](https://github.com/RadeonOpenCompute/ROCm/issues/451#issuecomment-422836032), we currently do not offer support for gfx8 GPUs without PCIe atomics. It's not just a question of achievable performance. At this time, our gfx8 GPUs require PCIe atomics to function properly in the ROCm environment. Unfortunately, adding support to our hardware, software, and firmware to work with HSA queues and signals without atomics is not as simple as just "disabling atomics".

**Comment by MoneroCrusher** [comment]
Hi @jlgreathouse 
Thanks for your input.

> Thus, I suspect you are right that the reason you are unable to see your GPUs is because you do not have PCIe atomics support for your large number of 1x slots. This is probably because these slots sit behind a PCIe switch that, to reduce costs, was not designed to route/forward atomic operations.

So this means that the x16 slot takes it's lanes from the CPU and that's the reason it has atomics / it supports my Lexa 550 (gfx 8)? If so, would you know if the x1 slots are "hardwired", or would there be a possibility to hack the motherboard BIOS and dynamically route the CPU lanes to the x1 slots individually?
If not, do you know of a atomics PCIE splitter that splits a x16 lane into 12 x1 lanes?
If not, is there any other way to resolve this besides getting another motherboard?

> At this time, our gfx8 GPUs require PCIe atomics to function properly in the ROCm environment. Unfortunately, adding support to our hardware, software, and firmware to work with HSA queues and signals without atomics is not as simple as just "disabling atomics".

So is it fundamentally different to disable the Atomics requirement for gfx 8 (in comparison to gfx 9)?
I think the ROCm team should make a decision here.
There are millions of polaris card out there that currently can't be used for Tensorflow (or is there an AMDGPU Pro implementation?). As a comparison GFX 9 GPUs are a much smaller subset and smaller amount of Exaflops. By enabling GFX 8 support you are opening the door for potentially many people like myself to explore the world of AI/ML/DL.
I really do hope that there is a way.

**Comment by jlgreathouse** [comment]
Hi @MoneroCrusher 

Yes, it's likely that your x16 slot is connected directly to the CPU's PCIe root complex. Considering [Intel's ark entry for your CPU](https://ark.intel.com/products/97452/Intel-Celeron-Processor-G3930-2M-Cache-2-90-GHz-) claims that it has a total of 16 PCIe lanes, I would wager that all of your other lanes hang off a PCIe switch connected [through the PCH chipset](https://ark.intel.com/products/98086/Intel-B250-Chipset). The [B250 datasheet](https://www.intel.com/content/www/us/en/chipsets/200-series-chipset-pch-datasheet-vol-1.html?wapkw=200+series+chipset) only mentions base specification for PCIe 3.0, which means it does not support the PCIe-optional atomic operations.

I doubt you can make changes to the motherboard BIOS route those x1 slots directly into the CPU's PCIe controller. This sort of setup is related to whee the motherboard wires are actually routed. Based on the previous information, I don't believe you would be able to use atomics on any of these ports.

If you wanted to build your own board, we have had good luck with [Broadcom PEX switches](https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/), but that's obviously a bare chip and I don't have any splitter boards to recommend (since these chips are usually designed into motherboards or multi-GPU boards directly).

I give a much longer, more detailed description of why we currently require PCIe atomics on gfx8 in [the posts I linked previously](https://github.com/RadeonOpenCompute/ROCm/issues/451#issuecomment-422836032).

**Comment by MoneroCrusher** [comment]
Hi @jlgreathouse 
That's too bad that the x1 slots are directly routed to the chipset. The broadcom splitters seem to be hilariously expensive as well :/

> I cannot guarantee that we will be able to get this capability working on gfx8 GPUs, so for now those devices still require PCIe atomics to work within the ROCm software stack.

Could you say as much, as you're looking into it, or can you guys internally decide about it (or have you already)? As I said, there are Exaflops waiting to be used for all kinds of stuff, especially with current crypticurrency markets and Ethereum reducing their reward by 33% by next.

The timing to get people interested in alternatives is very good, so finally instead of bidding against each other in an ever increasing electricity war out of the respective cryptocurrency, people can apply their GPUs to do other important real world stuff.

**Comment by MoneroCrusher** [comment]
Just looking at all the comments of this article shows that there's a huge demand for Tensorflow enabled for GFX 8.
https://medium.com/tensorflow/amd-rocm-gpu-support-for-tensorflow-33c78cc6a6cf

**Comment by jlgreathouse** [comment]
Hi @MoneroCrusher 

I can say that it's on our "that would be nice to have" list. We have not completely discounted the possibility of offering atomic-free operation in gfx8. We understand the desire for this, as I mention [in this post](https://github.com/RadeonOpenCompute/ROCm/issues/451#issuecomment-422835753).

That said, I cannot make any public commitments for when, or if, AMD may enable such support.

We must trade off the development effort needed to enable this across multiple teams. For example: if this requires firmware changes in gfx8 GPUs, those teams may need to divert development time that is needed for bugfixes of current GPUs and feature development for future GPUs. Since firmware development may be shared across multiple projects, this could end up delaying gaming GPUs or causing feature loss for future non-ROCm workstation GPUs, etc. Unfortunately, these decisions are made in a larger ecosystem beyond just the ROCm team's desire to support these use-cases.

I am not trying to imply that we do not want to do this, nor that we may not in the future. I can only say that we have not yet made any public commitments to do so. I cannot offer any more details beyond that.

**Comment by MoneroCrusher** [comment]
> equires firmware changes in gfx8 GPUs

What do you mean by that? The VBIOS itself would have to be adjusted to work with ROCm?

> current GPUs and feature development for future GPUs

The RX 5xx series is 2017, I'd consider them "current"? Official release date for my Lexa Pros is April 2017. Release date for my Baffins is October 2017.

> I cannot offer any more details beyond that.

Lastly, can you tell me if the implementation of Atomics-free ROCm for GFX 9 fundamentally differs from GFX 8? If not, then there could maybe be a community fork?

**Comment by jlgreathouse** [comment]
> What do you mean by that? The VBIOS itself would have to be adjusted to work with ROCm?

There are other firmware besides our VBIOS. For example, you'll see that [this firmware commit](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/amdgpu?id=0f22c8527439eaaf5c3fcf87b31c89445b6fa84d) updates the firmware for multiple hardware blocks on Vega 10 GPUs. This includes hardware units such as the MEC, RLC, and SDMA blocks which can consume AQL packets sent to the GPU from HSA queues. As mentioned in one of my previously linked posts, the way these units would would potentially need significant modification to work with ROCm/HSA user-level queues without requiring PCIe atomics. This may require firmware modifications.

> The RX 5xx series is 2017, I'd consider them "current"? Official release date for my Lexa Pros is April 2017. Release date for my Baffins is October 2017.

Note that I said "bugfixes of current GPUs". I am not saying that we do not make firmware changes on gfx8 GPUs to fix bugs. [Take this new firmware push](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/amdgpu/polaris12_mec.bin?id=aeec108ba8ed8ced0694ea9137906c088b394edd), for example. Moving from "PCIe atomics required" to "optionally work without PCIe atomics" is an additional feature request, rather than a bug fix.

> Lastly, can you tell me if the implementation of Atomics-free ROCm for GFX 9 fundamentally differs from GFX 8? If not, then there could maybe be a community fork?

The on-chip engines are quite different between gfx8 and gfx9, so the implementation details that would need to change in these firmware blocks may be significantly different.
