### ISSUE TITLE
6+ Vega tdxminer mining

### ISSUE THREAD

**Issue by xenofobia** [RadeonOpenCompute/ROCm#441]
Hello. Is there any way to run more than 6 Vegas with rocm? I spent last 48 hours trying to run more by using different kernels etc. and still no result.

**Comment by gstoner** [comment]
We run 12 GPU on servers today.  The issue is your ussing consumer motherboard with out PLX PCIe Gen3  Swtich on x16 or x8 PCIe lane to support Polaris based GPU.   Only. Vega10 today supports abilty to use PCIe Gen2 in x1 lane if you shut off SDMA in 1.8.1 ( this is tempory for this release, future release it just work with SDMA on)  Also we working on getting Firmware addressed to support GFX 8 parts
