### ISSUE TITLE
Vega 64 power limit

### ISSUE THREAD

**Issue by Wacholek** [RadeonOpenCompute/ROCm#458]
Hi, 
In ROCm-SMI a OC function was implemented. There is possibility to change clock profile for GPU and memory ( does not work) and OC the highest GPU profile by setting --setoverdrive %. But in my case almost non of this does not matter because there is power limit of 220W. 
Is there any way to pass this 220W? Any extra power limit extension?

Recently I flashed my card with Vega 64 LC edition bios. There is a limit to 264W but still, I cannot use the full capability of the card and I am the stack to 1560MHz. This card is working flawlessly at 1770Mhz @365W so I am losing a lot of computing power. 
GPU voltage control would also be a very nice feature.

**Comment by tekcomm** [comment]
The limit is in there because of pci specs, to bypass the power limit would require you to mod the bios to the point it will and probably not function on windows and would only work on certain linux configurations .

**Comment by Wacholek** [comment]
What is so different on Linux drivers that I have to edit card bios to extended power limit? 
Under Windows I can increase power limit up to +50% so I don't think it is so hard-coded into Vega Bios.  Also frequency raport of Vega GPU is not accurate. Vega can adapt GPU freq with steps of 1MHz not by switching between GPU freq states. 
This is all done by Windows driver.  Why this cannot be done in ROCm? 

> This limits your power draw:
echo $MICROWATTS > /sys/class/drm/card0/device/hwmon/hwmon0/power1_cap

Can this extend power draw limit?

**Comment by Hackintoshihope** [comment]
Voltage and power consumption does not change with these patches. At the wall measured with a watt meter power consumption is stuck at 300W per card no matter the voltage setting. Did not know is this expected behavior or if Vega support is still in beta?

**Comment by tekcomm** [comment]
https://cgit.freedesktop.org/~agd5f/linux/log/?h=amdgpu

**Comment by preda** [comment]
@Wacholek , how are the GPU temperature and fan at 1770Mhz@365W ? (just curious; I find I have difficulty to cool 220W with the stock air cooler.)

**Comment by Wacholek** [comment]
I can't reach 1770Mhz. Under linux its locked to max 265W using Vega LC bios. Than its about 1535Mhz-1600Mhz than@42*C.
Under Windows in gaming I can reach 365W@1690Mhz@46*C. 
All my cards are under water with 9 fan radiator so no problem at all.

**Comment by preda** [comment]
@Wacholek thanks, that's impressively cool :)

**Comment by Wacholek** [comment]
Aktualny not that impresie. One of my AC has failed and I have 25*C in the room. When was 16*C my Vegas was kept at around 37*C.

**Comment by seansplayin** [comment]
I've got kernel 4.20 installed, now I just need to figure out the command to increase Vega64's Power Target
any ideas?

**Comment by jlgreathouse** [comment]
Hi @Wacholek, 

The change I discussed in my previous post has made it both into upstream [Linux as of 4.20](https://github.com/torvalds/linux/blob/v4.20/drivers/gpu/drm/amd/powerplay/amd_powerplay.c#L966) and into [ROCK as of ROCm 2.0.](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/roc-2.0.0/drivers/gpu/drm/amd/powerplay/amd_powerplay.c#L995). As such, you should be able to use either of these options if you still want to increase the maximum power limit on your AMD GPU.

In addition, [as of ROCm 2.0.0](https://github.com/RadeonOpenCompute/ROC-smi/blob/roc-2.0.0/rocm_smi.py#L1387), you should be able to use `rocm-smi --setpoweroverdrive N` to set the power cap of your GPU, where N is in watts.


Hi @v0idwalker,

The part of [my patch](https://github.com/torvalds/linux/commit/f7becf9a0803030ae125189823328e2d62b90f7b) that allows you to **read** `power1_cap_max` as higher than the default is on lines 1007-1013. In this case, if you have configured OverDrive to be enabled, the value returned by a read to that sysfs file will be `default power cap * (100% + VBIOS-specified maximum power limit increase percentage)`. For example, if your power cap was originally 165, and your VBIOS allows you to increase that by up to 50%, then (when OverDrive is enabled) this read would return 247 W.

The part that allows you to **write** a higher value than the default is on lines 982-988. If you have configured OverDrive to be enabled, it will not reject values that are below `default power cap * (100% + VBIOS-specified maximum power limit increase percentage)`

The important thing I've mentioned a few times here is that you must have OverDrive enabled on the `amdgpu.ppfeaturemask` module configuration variable. Otherwise, any such power boosting is turned off. See [this enum in the driver code](https://github.com/torvalds/linux/blob/v4.20/drivers/gpu/drm/amd/include/amd_shared.h#L114) to to know which bit to set in the mask to enable OverDrive.

Note also that the patch I linked sets the maximum power increase to `TDPODLimit`, which is specified by the VBIOS. As such, if your GPU card vendor (e.g. PowerColor) sets that to `0`, you will not be able to use this feature.


Hi @seansplayin,

You may want to see the above discussion for more details. However, the shortened version is:

- Make sure you have OverDrive enabled in your `ppfeaturemask`. [In this case](https://github.com/torvalds/linux/blob/v4.20/drivers/gpu/drm/amd/include/amd_shared.h#L114) (kernel 4.20), you would want to make sure that you set the following kernel parameters `amdgpu.ppfeaturemask=0xfffd7fff`. I set this particular mask because [the default value of this mask in v4.20](https://github.com/torvalds/linux/blob/v4.20/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c#L118) is `0xfffd3fff`. And the OverDrive feeature is set by ORing in `0x4000`.
- As discussed above, you could directly read `/sys/class/drm/cardN/device/hwmon/hwmon0/power1_cap_max` (where "N" is the GPU number) to see the maximum power cap of that GPU in milliwatts. You could then write into `/sys/class/drm/cardN/device/hwmon/hwmon0/power1_cap` to change your GPU's current power cap. You can write `0` into `power1_cap` to reset the the value to its default.
  - Alternately, you could use `rocm-smi --setpoweroverdrive N` to set the maximum power cap. It will not allow you to set it more than the driver-imposed limit, which you can read with `rocm-smi --showmaxpower`
  - Reading `rocm-smi`'s [Python code for setting the power cap](https://github.com/RadeonOpenCompute/ROC-smi/blob/roc-2.0.0/rocm_smi.py#L1065) may also be useful in understanding what steps you need to go through if you want to do this manually.
