### ISSUE TITLE
ROCm-1.3 linker problem.

### ISSUE THREAD

**Issue by briansp2020** [RadeonOpenCompute/ROCm#47]
I tried to build my code at [cs344 Problem Set 1](https://github.com/briansp2020/cs344/tree/master/Problem%20Sets/Problem%20Set%201) and I get errors.

> $ make
hipcc -o HW1 main.o student_func.o compare.o reference_calc.o -L /usr/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -g -hc -std=c++amp
/opt/rocm/hcc-lc/compiler/bin/clamp-link: line 302: cd: /home/briansp/git/cs344/Problem: No such file or directory
objdump: 'main.o': No such file
objdump: 'student_func.o': No such file
objdump: 'compare.o': No such file
objdump: 'reference_calc.o': No such file
ld: cannot find main.o: No such file or directory
ld: cannot find student_func.o: No such file or directory
ld: cannot find compare.o: No such file or directory
ld: cannot find reference_calc.o: No such file or directory
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
Died at /opt/rocm/bin/hipcc line 365.
Makefile:37: recipe for target 'student' failed
make: *** [student] Error 1

Then, I copy the code to ~/dev/cs344 and it builds fine. It looks like the linker is not handling space in the path properly. I'm reporting it here since I'm not sure whether the linker is part of llvm or hcc or clang or lld.

**Comment by gstoner** [comment]
Is this 16.04. If so we found known issue in GCC tool supplied with 16.04.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Nov 11, 2016 at 11:52 PM -0600, "Brian" <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried to build my code at cs344 Problem Set 1<https://github.com/briansp2020/cs344/tree/master/Problem%20Sets/Problem%20Set%201> and I get errors.

$ make
hipcc -o HW1 main.o student_func.o compare.o reference_calc.o -L /usr/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -g -hc -std=c++amp
/opt/rocm/hcc-lc/compiler/bin/clamp-link: line 302: cd: /home/briansp/git/cs344/Problem: No such file or directory
objdump: 'main.o': No such file
objdump: 'student_func.o': No such file
objdump: 'compare.o': No such file
objdump: 'reference_calc.o': No such file
ld: cannot find main.o: No such file or directory
ld: cannot find student_func.o: No such file or directory
ld: cannot find compare.o: No such file or directory
ld: cannot find reference_calc.o: No such file or directory
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
Died at /opt/rocm/bin/hipcc line 365.
Makefile:37: recipe for target 'student' failed
make: *** [student] Error 1

Then, I copy the code to ~/dev/cs344 and it builds fine. It looks like the linker is not handling space in the path properly. I'm reporting it here since I'm not sure whether the linker is part of llvm or hcc or clang or lld.

-

**Comment by briansp2020** [comment]
Yes 16.04

**Comment by scchan** [comment]
I opened a new issue against hcc (RadeonOpenCompute/hcc#161) and will continue to track it there

**Comment by briansp2020** [comment]
Looks like this is fixed in ROCm 1.3.1
