### ISSUE TITLE
Feature request sql integration of rocm-smi 

### ISSUE THREAD

**Issue by tekcomm** [RadeonOpenCompute/ROCm#483]

**Comment by jlgreathouse** [comment]
Hi @tekcomm 

Sorry for the delay in responding to this. I think this sounds like an interesting feature, though I'm not sure if our internal development teams would have time to put this on our roadmap -- development and verification resources being what they are, I can't promise that we would be able to spare the resources for a feature that (while admittedly potentially useful) doesn't have a lot of customer demand.

That said, I see that your git repo is a README that describes the end result, but doesn't include the code. Would you be interested in sending me a note, potentially with access to the code you use to do this? If it's not a tremendous amount of extra complexity, I could try to see if our teams would upstream your rocm-smi changes.

Thanks!

**Comment by tekcomm** [comment]
I already added it in to the rocm-smi on my server

On Mon, Aug 13, 2018 at 1:01 PM, Joseph Greathouse <notifications@github.com

**Comment by tekcomm** [comment]
Its in production and the code is up on the github

**Comment by jlgreathouse** [comment]
Great, thanks for putting the code up. Let me take a look at it, and then pass around the details internally.

First question that comes to mind: I suspect our normal users wouldn't want to always have SQL printed to the screen, so we would want to have a command-line option for this. When that command line option is set, do you have any thoughts on what we should do with errors? Right now, we log errors directly to stdout, which seems like it would interfere with your SQL insert statements. For instance, on my system where one of my GPUs doesn't support power monitoring:
```
$ ./rocm_smi-mysql
INSERT INTO miner_stats (gpu,temp,avgpwr,sclk,mclk,fan,perf,od,hostname) VALUES GPU[1]          : WARNING: Empty SysFS value: power
('g1','46.0','Error','300','150','20.0,'auto','0','sysname'),('g0','42.0','4.0','852','167','11.76,'auto','0','sysname');
WARNING: One or more commands failed
```

The two WARNING lines -- in this mode should they be suppressed? Or logged somewhere else (e.g. stderr so that you can redirect them away from the normal stdout SQL statement)? Thoughts on this, since you're the first (and so far only) user of this proposed mode. :)

**Comment by tekcomm** [comment]
I only had 1/2 a hour to work on it so up 2 u :)  I push it to stderror
The main thing is to keep it in one line so that it does a multi insert and
it is non-blocking so it can handle 800,000 gpus

On Mon, Aug 13, 2018 at 3:10 PM, Joseph Greathouse <notifications@github.com

**Comment by tekcomm** [comment]
Currently rippa is on 1.7 gigawatts of gpus & asics

**Comment by tekcomm** [comment]
However ya want it ill recode it this weekend.

**Comment by jlgreathouse** [comment]
Let me take a stab at some changes that I'll pass around internally. If they aren't too bad, I'll submit a PR to your repo so you can try them out and see if they meet your needs.

**Comment by tekcomm** [comment]
Thanks :) I have a bit of work this week helping out a smaller customer
with 3000 gpus. So let me know what changes Ill be done this weekend and
have time

On Mon, Aug 13, 2018 at 3:44 PM, Joseph Greathouse <notifications@github.com

**Comment by jlgreathouse** [comment]
Looks like it'll be a bit before I can try some internal changes -- we might need to sync on this after ROCm 1.9 comes out. rocm-smi in 1.9 will have some changes that we'll need to work with if we want to explore this request.

**Comment by tekcomm** [comment]
I was always from the less is more school, anything ya want removed is no
problem :). I got alot of people running the vega's/550 on the older stacks
against the edge and mainline kernels now that 4.18rc8 is working with the
kfd and pp code..

On Tue, Aug 14, 2018 at 6:32 PM, Joseph Greathouse <notifications@github.com
