### ISSUE TITLE
Can't initialize rocm driver for rx570

### ISSUE THREAD

**Issue by nazarpechka** [RadeonOpenCompute/ROCm#622]
I am currently running such a setup:
MB - Msi z270 A pro
CPU - intel core i3-7100
GPU - AMD Rx 570, installed in second x16 pcie 3.0 slot
RAM - 8gb ddr4
Kernel - 4.10.17
OS - Ubuntu 16.04

Before i had amdgpu-pro drivers installed, but now i want to use tensorflow with my amd gpu. So i uninstalled amdgpu-pro, installed rocm, but when i try running python tensorflow script, i get an error:
`2018-11-25 13:14:06.572026: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
terminate called after throwing an instance of 'ihipException'
  what():  std::exception`

Command `dmesg | grep 'kfd'` gives this output:
`[   17.588141] kfd kfd: Initialized module
[   17.642852] kfd kfd: skipped device 1002:67df, PCI rejects atomics`

Overall, something seems to be wrong with PCIe atomics support in my setup, but all components seem to be compatible. Thanks.

**Comment by briansp2020** [comment]
> GPU - AMD Rx 570, installed in **second** x16 pcie 3.0 slot

Why second slot? Usually, unless the MB support Cross Fire or SLI, only the first slot supports PCIe 3 with atomic operation.

**Comment by nazarpechka** [comment]
> Why second slot? Usually, unless the MB support Cross Fire or SLI, only the first slot supports PCIe 3 with atomic operation.
First slot isnt working, it burned out a year ago for some reason. i have another motherboard with working slot, but i can replace it if its really necessary

**Comment by nazarpechka** [comment]
> amdkfd needs to be added to initramfs BEFORE video driver. 

Could you share how to do this?

>Second AMDGPU-PRO does not work with this

I mentioned in post that i had it before, but uninstalled it before installing rocm. Can it still be a problem?

>Third, if you're using Arch Linux binaries must be rebuilt with every kernel upgrade.

I'm on ubuntu

**Comment by maxcr** [comment]
`https://wiki.ubuntu.com/Initramfs`

I haven't used Ubuntu in years but it shouldn't be too difficult.

**Comment by jlgreathouse** [comment]
Hi @nazarpechka 

The issue is that the PCIe slot you're using does not support PCIe 3.0 atomics between your CPU and your GPU. Looking at your [motherboard's specification page](https://www.msi.com/Motherboard/Z270-A-PRO/Specification), this board claims that the 2-slot solution is supported in "x16/x4 mode". However, if I look at the [Ark specification page for your processor](https://ark.intel.com/products/97455/Intel-Core-i3-7100-Processor-3M-Cache-3-90-GHz-), your CPU only supports a total of 16 directly-connected lanes (in "1x16, 2x8, 1x8+2x4" modes).

As such, I strongly suspect that the second PCIe slot on your motherboard is connected through the chipset and does not support forwarding PCIe atomics between the processor and the GPU. You can see this in the KFD output that says `[ 17.588141] kfd kfd: Initialized module [ 17.642852] kfd kfd: skipped device 1002:67df, PCI rejects atomics`.

That said, if you really want to verify this, you can build a new version of [lspci](https://github.com/pciutils/pciutils) (the one in Ubuntu 18.04 is too old to show atomics) and see the connections between your CPU and your GPU using `./lspci -t`. You can then look at each of the devices between your CPU and GPU and see if they support atomics using `./lspci -vvv` and looking for `AtomicOpsCap:` field.
