### ISSUE TITLE
cross lane operation `__builtin_amdgcn_readlane`

### ISSUE THREAD

**Issue by psychocrypt** [RadeonOpenCompute/ROCm#627]
I try to use the cross lane operation `__builtin_amdgcn_readlane` in OpenCL on Rocm 1.9 with a VEGA64.
The code is compiling but the result from the operation is always wrong:

```C++
            uint dest;
            uint src = get_local_id(0)  ;
            int lane = (get_local_id(0) + 1) %8 ;
            dest = __builtin_amdgcn_readlane(src,lane);
            __builtin_amdgcn_s_waitcnt(0);
            printf("read %u -> %u|%u\n",get_local_id(0),dest, lane);
```
The result in `dest` is always `1`
```
read 5 -> 1|6
read 6 -> 1|7
read 7 -> 1|0
read 0 -> 1|1
read 1 -> 1|2
```

But must be `(get_local_id(0) + 1) %8`.

If I hard code that all threads must read from lane e.g. 3 `dest = __builtin_amdgcn_readlane(src,3);` the result is for all `4` (correct!!).

I can not find any documentation or examples for the intrinsic. 
1. Could it be that variable lane address are not supported?
2. Is `__builtin_amdgcn_s_waitcnt` required after `__builtin_amdgcn_readlane`?

**Comment by jlgreathouse** [comment]
Hi @psychocrypt 

I should probably ask what you're expecting to see as output from your test. Are you trying to have each vector lane read the values of the lane next to it? If so, `v_readlane_b32` (which is the GCN instruction emitted by the `__builtin_amdgcn_readlane()` intrinsic) is not what you're looking for. The [Vega ISA guide](https://developer.amd.com/wordpress/media/2017/08/Vega_Shader_ISA_28July2017.pdf) describes `v_readlane_b32` as:
> Copy one VGPR value to one SGPR. D = SGPR-dest, S0 = Source Data (VGPR# or M0(lds-direct)), S1 = Lane Select (SGPR or M0).

As such, the output of this instruction goes into a _scalar_ register and thus all lanes in a wavefront will always see the same value. The lane you are reading from is defined by scalar argument S1 (which should be the second argument to `__builtin_amdgcn_readlane()`). Because this is a scalar argument, it cannot differ across a wavefront's lanes. Essentially, this instruction is meant for pushing the value from one lane into all other lanes.

If you are trying to have every lane read from its neighbor (sort of like a cross-lane shift operation) then you should look into `ds_swizzle_b32`, `ds_permute_b32`, `ds_bpermute_b32`, or `v_mov_b32` using DPP extensions. [This blog post](https://gpuopen.com/amd-gcn-assembly-cross-lane-operations/) may be helpful in describing the usage of these various operations. [This presentation](https://gpuopen.com/gdc2017-advanced-shader-programming-on-gcn/) also includes some extra information about this.

You can find the LLVM builtins for these instructions [here](https://github.com/RadeonOpenCompute/clang/blob/roc-1.9.x/include/clang/Basic/BuiltinsAMDGPU.def#L90). Note that the DPP move intrinsic did not appear until gfx8 ("Volcanic Islands" / "GCN3"), so it will not work on Hawaii GPUs (whcih are gfx7, "Sea Islands").

**Comment by psychocrypt** [comment]
@jlgreathouse Thank you for the feedback.

I also tried `__builtin_amdgcn_ds_bpermute`

```C++
            uint dest;
            uint src = get_local_id(0)  ;
            int lane = (get_local_id(0) + 1) %8 ;
            dest = __builtin_amdgcn_ds_bpermute(src,lane);
            __builtin_amdgcn_s_waitcnt(0);
            printf("read %u -> %u|%u\n",get_local_id(0),dest, lane);
```

but it is also not working. The blog entry https://gpuopen.com/amd-gcn-assembly-cross-lane-operations/ is not helping at this point because it shows the native ISA command with different function signature than the implementation in clang. The problem is that there is no open documentation available about the usage and behavior.
What I try is to read a value from the neighbor lane inside of a group of 8 threads (like NVIDIA `shuffle`).

Could you please provide me a snipped where each lane is reading from the higher lane mod 8?

```
//lane  readFrom
0 1
1 2
2 3
3 4
4 5
6 7
7 0
```

**Comment by psychocoderHPC** [comment]
I verified that HDF5/splash is the source of all the pain. I manipulated PIConGPU that we write with 8 GPUs each X elements (4byte per elem) so hat I wrote accumulated dataset <4GiB and >4GiB.
```
X byte_accumulated status
134217727 <4GiB OK
134217728 =4GiB OK
134217729 >4GiB Fail
```
The reason why 134217728 is working is that the size is to large but there is no access after 4GiB.

Task todo: Write I mini app to check if this behaviour is coming frmom libSPlash or pure HDF5.

https://portal.hdfgroup.org/pages/viewpage.action?pageId=48808714 is saying
```
What is the limit on the chunk size?
The current maximum number of bytes in a chunk is 2^32-1 (4 GB). As a result of this restriction, the number of elements in a chunk cannot be greater than 4 GB. You must also account for the datatype size of each element.

The chunk size can be larger than a dataset's dimension if the dataset's maximum dimension sizes are declared as unlimited or if the chunk size is less than the maximum dimension size. The chunk size for fixed-size datasets cannot exceed the size of a fixed-size dataset. For example, a dataset consisting of a 5 x 4 fixed-size array cannot be defined with 10 x 10 chunks, as the following error will occur:
```
but since each MPI rank has its own dataset this should not be the limitation.



Tested with HDF5 18.8.20 on hemera

**Comment by jlgreathouse** [comment]
Hi @psychocrypt 

The LLVM builtin syntax is essentially identical to using the assembly instruction, so the [ISA manual for your target GPU](https://developer.amd.com/wordpress/media/2017/08/Vega_Shader_ISA_28July2017.pdf) is the best place to learn how to use these. Note, however, that builtins offer a better interface to the compiler than inline assembly (since the compiler knows what their full inputs, outputs, and side effects are, rather than treating them as black boxes that cannot be optimized around.

On Page 155 of the above-linked manual, you'll find the definition for `ds_bpermute_b32`, the assembly instruction generated by `__builtin_amdgcn_ds_bpermute()`. This instruction takes three register values: `DATA0` (the source variable to pull data from), `ADDR` (the lane to pull data from), and `VDST` (the variable to store the result into). The output of the builtin is obviously VDST, so the question for the two inputs is which is `DATA0` and which is `ADDR`. For these particular ops, [this post](https://github.com/RadeonOpenCompute/ROCm/issues/189#issuecomment-325763087) shows that the first is the `ADDR` (which lane to pull from) and the second is `DATA0` (what data to pull). You can also see this in the [tests for this operation within the compiler](https://github.com/llvm-mirror/llvm/blob/release_70/test/CodeGen/AMDGPU/llvm.amdgcn.ds.bpermute.ll).

An important thing to note in the ISA manual is:
>"Note the address passed in is the thread ID multiplied by 4. This is due to a limitation in the DS hardware design.

As such, the value that you pass into `ADDR` needs to be 4x the target thread. So you should be able to change your code block to the following to do what you want:

```c
uint dest;
uint src = get_local_id(0)  ;
int lane = ((get_local_id(0) + 1) % 8) << 2;
dest = __builtin_amdgcn_ds_bpermute(lane, src);
__builtin_amdgcn_s_waitcnt(0);
printf("read %u -> %u|%u\n",get_local_id(0),dest, lane);
```

Finally, [this post](https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/43#issuecomment-423001693) may be somewhat useful for you.

**Comment by psychocrypt** [comment]
@jlgreathouse big thanks for you help!

For everyone who came from the CUDA world. The magic was to multiply the "lane" by 4.
