### ISSUE TITLE
ROCm Performance Issues...

### ISSUE THREAD

**Issue by briansp2020** [RadeonOpenCompute/ROCm#633]
https://www.phoronix.com/scan.php?page=article&item=rocm19-nvidia415-compute&num=3

I thought the whole idea behind HSA/ROCm was to reduce kernel launch latency overhead. How is it that NVidia has so much lower latency? Is NVidia doing similar thing to HSA for kernel launch? How much more room for improvement in AMD's code is there? Is the bottleneck software? firmware? or something else?

Just curious. I did not expect AMD to lose so badly in latency measure against NVidia...

**Comment by foobar2019** [comment]
ROCm is an optimizing compiler toolchain, bleeding edge llvm as opposed to the poor ancient thing which comes with stock driver. You can get fancy things like int24 and tight control over compiler result, but it can't fix inheherent limits of GCN architecture. Such as the latencies - frequently just GDDR5 NV CU shared bus vs GCN+HBM tightly banked to CUs.

When you strip all the marketing bullshit, AMD boils down to being awesome as an open architecture, but meh choice if the plan is standard throwing hardware, not dev effort at the problem. Because of the openness, it can beat NV by far when you choose to exploit it and work close to the metal - NV being a profound black box compared to that. Yet NV is far more "cpu-like", friendlier to high level, sprawling kernels which can afford to be less aware of the metal itself.

**Comment by briansp2020** [comment]
Closing since this is very old
