### ISSUE TITLE
Is ROCm 2.0 waiting on Kernel 4.20 Release?

### ISSUE THREAD

**Issue by emerth** [RadeonOpenCompute/ROCm#636]
Is ROCm 2.0 waiting on kernel 4.20 release?

I know I keep bugging you guys about this, and I am truly grateful for the work that has gone into ROCm. I just want to understand where it is at in terms of release. 

Places like phoronix report ROCm 2.0 is essentially ready, but my experiences this summer/fall with the Linux 4.19 and 4.20 release candidates make me think the hold up is official OS support. Is this correct?

Thanks again!

**Comment by bill-mcgonigle** [comment]
Previous messages said 4.19 and EOY for 2.0 (it's not EOY yet...)  I sure hope that's still the case as many distros are targeting 4.19 as the next platform for their releases (e.g. Debian Buster).  Eagerly awaiting solid OpenCL on Buster here...

**Comment by emerth** [comment]
> 
> 
> ...it's not EOY yet...

To be sure. It just almost EOY.

**Comment by jlgreathouse** [comment]
Couldn't answer this before the release, since we always like to have a bit of wiggle room on release dates. For example, we might have to delay a release if we find any new major bugs right before release. That didn't happen this time. :)

ROCm 2.0 is out now, and no, we were not waiting on 4.20. We hope to keep on a regular release cycle, so hopefully we'll have ROCm working there soon after it's official.
