### ISSUE TITLE
clGetPlatformIDs(-1001) on Hawaii GPU with ROCm 2.0

### ISSUE THREAD

**Issue by Hobbes921** [RadeonOpenCompute/ROCm#668]
Good evening

After updating my ROCm setup to v2.0 via apt my OpenCL setup is broken.
I managed to fix the issue with missing firmware files (#640),
but executing clinfo now runs into 
``ERROR: clGetPlatformIDs(-1001)``
Calling ``clinfo -v`` just shows the same error.

Do you have an idea where this could come from?

My system is a Ubuntu 18.04.1 (4.15.0-43-generic) with two R9 390 (Hawaii) GPUs
and two Xeon E5-2690 v0 CPUs.
The previous version of rocm (1.9.x), installed via Debian PPA as well,
worked fine on this machine.

Please let me know if you need further information.

**Comment by jlgreathouse** [comment]
I believe I know what the problem is. Could you try modifying the following line and then rebuilding the ROCm OpenCL runtime? (You can find scripts in the [Experimental ROC project](https://github.com/RadeonOpenCompute/Experimental_ROC/tree/roc-2.0.0) for rebuilding the OpenCL runtime)

In [rocdefs.hpp](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/roc-2.0.0/runtime/device/rocm/rocdefs.hpp#L61), the line with `HSA_HAWAII_ID` looks like the following:
```
    /* TARGET HAWAII */ {HSA_HAWAII_ID, "", "hawaii", "", "Hawaii", 4, 16, 1, 256, 64 * Ki, 32, 0, 0, false},
```
Could you change it to instead say the following?
```
    /* TARGET HAWAII */ {HSA_HAWAII_ID, "", "hawaii", "gfx701", "Hawaii", 4, 16, 1, 256, 64 * Ki, 32, 0, 0, false},
```

If, for example, you are using Ubuntu 18.04, you should be able to run the following Experimental ROC scripts to rebuild the ROCm OpenCL runtime:

1. `distro_install_scripts/Ubuntu/Ubuntu_18.04/src_install/component_scripts/01_07_opencl.sh --get_code_only --source_dir ~/rocm_src/` This will download the source code for the ROCm OpenCL runtime
2. Modify `runtime/device/rocm/rocdefs.hpp` based on what I described above
3. `distro_install_scripts/Ubuntu/Ubuntu_18.04/src_install/component_scripts/01_07_opencl.sh --required` to install the software needed to build the ROCm OpenCL Runtime
3. `distro_install_scripts/Ubuntu/Ubuntu_18.04/src_install/component_scripts/01_07_opencl.sh --source_dir ~/rocm_src/ --package ~/rocm_packages/ --local` This will build the modified ROCm OpenCL runtime .deb packages and put them into `~/rocm_packages`. You can choose to install them with `dpkg` after that.
4. Alternately, you could run `distro_install_scripts/Ubuntu/Ubuntu_18.04/src_install/component_scripts/01_07_opencl.sh --source_dir ~/rocm_src/`, which will install the modified ROCm OpenCL Runtime into `/opt/rocm/` on top of anything else you installed there, but it will **not** create/install this a .deb package

**Comment by dmikushin** [comment]
@jlgreathouse Thanks. I've created a stripped version of OpenCL runtime, that can build everything except the compiler and generated bytecodes in reasonable times (we have to cope with consumer-level machines here): https://github.com/apc-llc/ROCm-OpenCL-Runtime

So far, there is no difference in the error after the change you suggested:

```
$ bin/clinfo
ERROR: clGetPlatformIDs(-1001)
```

**Comment by dmikushin** [comment]
From debugging clinfo I get the following:

clIcdGetPlatformIDsKHR () from /opt/rocm/opencl/lib/x86_64/libamdocl64.so returns **-32** in
khrIcdVendorAdd (libraryName=0x63eed0 "libamdocl64.so") at /home/dmikushin/apc/ROCm-OpenCL-Runtime/api/opencl/khronos/icd/icd.c:106

And then it comes down to error -1001 after that.

**Comment by jlgreathouse** [comment]
Hi @dmikushin 

I just rebuilt the entire OpenCL runtime using my directions above (on a pretty weak consumer desktop, for what it's worth; it took a while). I was able to bypass the error you're seeing. Please see this post in #640 for more details on the steps you will likely need to take to get OpenCL working on Hawaii in ROCm 2.0.

I'm not sure what you are generating by building "everything but the compiler", because our OpenCL runtime (which is contained in `libamdocl64.so` includes both the code changes I mention above, as well as our compiler which will generate OpenCL code. I would strongly recommend building the whole thing (e.g. with the script commands I show above) and see if that fixes your problem. It did for me.

**Comment by Hobbes921** [comment]
Hello @jlgreathouse 

I just tried to build ROCm 2.0 on my new test setup.
It all worked fine until 94% of compilation, but then it complained about the missing include file ```oclc_correctly_rounded_sqrt_off.amdgcn.inc```.
This file does not exist at all on the filesystem...

Newest state of git repo, cloned yesterday.
I executed exactly the commands you listed above.

Can someone confirm this?

**Comment by dmikushin** [comment]
It seems there is some broken dependency around .inc files in CMake scripts. I had a similar issue while building and successfully worked around it: https://github.com/RadeonOpenCompute/ROCm/issues/640#issuecomment-454610837 https://github.com/RadeonOpenCompute/ROCm/issues/640#issuecomment-454615557

**Comment by Hobbes921** [comment]
Thank you for the hint @dmikushin 
I just got the opportunity to replace my two R9 390 with an RX Vega 56.
This one is buggy as well, but I'll open up another issue for it.

To help other people having issues with their Hawaii GPUs on ROCm 2.0:

**I could fix my R9 390 test setup at home with a rollback to ROCm 1.9.2**

### Rollback to ROCm 1.9.2

- Remove any parts of current ROCm setup
```sudo apt autoremove rocm-dkms rocm-dev rocm-utils```

- Clone experimental project
```git clone https://github.com/RadeonOpenCompute/Experimental_ROC.git```

- cd into project directory
```cd Experimental_ROC```

- switch to 1.9.2
```git checkout roc-1.9.2```

- run preparation script
```distro_install_scripts/Ubuntu/Ubuntu_18.04/deb_install/00_prepare_system_ubuntu_18.04.sh```
_will prompt to reboot after finish -> confirm with 'y'_

- run setup
```distro_install_scripts/Ubuntu/Ubuntu_18.04/deb_install/01_install_rocm_ubuntu_18.04.sh```
_Will prompt to execute script 02 after finish -> confirm with 'y'_

- reboot again and you're back to ROCm 1.9.2

**HINT:** 
If apt complains about unresolved dependencies, there might be some packages left from newer setup.
You can remove them with
```sudo apt autoremove hip_* hsa*```

**IMHO:**
It would be great of course to bring ROCm 2.0 to Hawaii GPUs as well,
but I think most users need their systems up and running instead of using them for hunting bugs.

Thank you very much for your help, @dmikushin  and @jlgreathouse .
I will close this one then.
