### ISSUE TITLE
HSA process got unhandled exception

### ISSUE THREAD

**Issue by iotamudelta** [RadeonOpenCompute/ROCm#69]
I have here a supermicro workstation with 2x R9 Nano and 2x S9150 installed running Ubuntu 16.04. This setup worked well with amdgpu-pro 16.40 previously.

I removed amdgpu-pro and installed ROCm 1.4 following instructions. However, the basic HSA sample (vector_copy) segfaults in libhsa-runtime64. dmesg shows a GPU fault detected, VM_CONTEXT1_PROTECTION_FAULT and VM fault.

Running any (previously working) OpenCL code or even just running clinfo causes "kfd: HSA Process (PID $$$$) got unhandled exception". After this, the executable hangs and after killing it dmesg contains kfd: cp queue preemption time out and amdkfd: Resetting wave fronts on dev.

What do I need to do to get this setup to work?

**Comment by gstoner** [comment]
Can we start simple,  start with 1 GPU in the system and let get Vector copy working.   Also which Supermicro system is it.

**Comment by iotamudelta** [comment]
Dear Greg,

thanks for your response! A single S9150 causes the same issue as described above. A single R9 Fury works, however at a seemingly 2-3x reduced performance compared to amdgpu-pro 16.40 for our in-house OpenCL code (both for single and double precision kernels and for both tests using clFFT calls and those that don't). Is the later expected?

The Supermicro system is a SYS-7048GR-TR. It has 2 Intel Xeon E5-2620 V4 alongside 64 GB DDR4 installed.

Let me know if I can provide more information.

**Comment by gstoner** [comment]
Not expecting 2x drop in performance. The compiler is still early in development. With this release we were really looking functionality testing not performance.  Wonder if it has to do with how clFFT works since it does search space optimization using the JIT.  It why we working on rocBLAS which is even more Optimized for ROCm stack.  Really we need to profile it.


We use the same 7048GR-TR for Development, so we could do performance test in house, if you like. We can follow up up my AMD email address,  my firstname.lastname@amd.com<http://amd.com>   greg stoner.  The S9150 should not be a issue in the system, we run them as well.

Greg

On Jan 4, 2017, at 11:34 AM, iotamudelta <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Greg,

thanks for your response! A single S9150 causes the same issue as described above. A single R9 Fury works, however at a seemingly 2-3x reduced performance compared to amdgpu-pro 16.40 for our in-house OpenCL code (both for single and double precision kernels and for both tests using clFFT calls and those that don't). Is the later expected?

The Supermicro system is a SYS-7048GR-TR. It has 2 Intel Xeon E5-2620 V4 alongside 64 GB DDR4 installed.

Let me know if I can provide more information.
