### ISSUE TITLE
Opencl sample codes on ROCm platform ? 

### ISSUE THREAD

**Issue by VishwasRao17** [RadeonOpenCompute/ROCm#73]
Do we have a sample codes in openCL language on ROCm platform. 
Any other sample codes which will offload job to gpu ? in any language HIP / OpenCL / HCC . 
This will help me in understanding the flow of instructions ?

**Comment by jedwards-AMD** [comment]
There are samples for HIP in the /opt/rocm/hip/samples directory. For OpenCL, you should be able to use many of the available OpenCL applications. There are some features of OpenCL not supported on the ROCm OpenCL runtime (the biggest being images), but basic OpenCL functionality should be the same.

**Comment by VishwasRao17** [comment]
@jedwards-AMD Thank you. I will go through the HCC samples available over the same directory. It says the source codes of runtime apis are available. This might help me. Also a quick question, does the wrapper src code which binds opencl apis to rocm are available ?

**Comment by nevion** [comment]
@VishwasRao17 pet-peev - please say source code, not and preferably never use codes.

 I can't understand what your question is but you don't have to do anything special to get OpenCL to run on ROCm provided you're loading their libOpenCL.so.   Go read up on an existing OpenCL application such as clinfo (there are many variants available on github) rather than file an issue here.  This question does not seem to be ROCm specific...

**Comment by jedwards-AMD** [comment]
The OpenCL on ROCm source code is not yet available. I assume this is what you meant with the term "wrapper src code".
