### ISSUE TITLE
ROCm 2.7 does not support Hawaii. Readme needs updating

### ISSUE THREAD

**Issue by JMadgwick** [RadeonOpenCompute/ROCm#871]
Support for Hawaii (gfx700/1) has been broken since ROCm 2.0 (#691 and also #640) which was released 8 months ago. The original issue appeared to be with firmware files (which was fixed) but the later issue (execution failure) has not been fixed since then and nothing has changed (#784).

At this point it really doesn't look like this is going to get fixed. Both OpenCL and HIP/HCC programs hang on execution and so ROCm is currently of no use on Hawaii GPUs.

I only revisited Hawaii today because I was going to make a tutorial showing installation and operation of ROCm/HIP. With this is mind it seems to be unhelpful and misleading to list Hawaii as a supported GPU ([even if "support is not guaranteed"](https://github.com/RadeonOpenCompute/ROCm#supported-gpus)).

**Comment by walterav1984** [comment]
Would rather see it fixed than removing the false hope from the README.md, but I understand @JMadgwick. 

Just a reminder we're talking about lacking/neglecting support after 3 years and a short while from purchase of the hardware(not talking windows/macos). With a lot of open drivers and compute developments from AMD I would have expected a longer invest value especially on the linux side, but maybe that is reserved for VEGA or NAVI or even beyond. Trying to comprehend...

Looking at #640 more specific @jlgreathouse his [1st patch](https://github.com/RadeonOpenCompute/ROCm/issues/640#issuecomment-454883156) [2nd patch](https://github.com/RadeonOpenCompute/ROCm/issues/640#issuecomment-454883156) and looking at the last comment @umar456 it indeed seems there a still segfaults.

Still would like to see Davinci Resolve 16 with Rocm and r9 390x though.

**Comment by Bengt** [comment]
Even the next-younger gfx803 has massive issues that make at least tensorflow-rocm not viable for many use cases:

<https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/479>

So, I would suspect gfx7 products to have practically reached end of their support period, too. 3 years seems to be a long period for AMD ROCm development. Their policy seems to be to raise the quality as much as possible for the latest products and to maintain support for older products as much as possible with minimum effort. I can respect that, because AMD's Radeon Technology Group needs to focus it's limited resources on the areas that matter most. However, documenting the support or even functional hardware status would be an honest step in the direction of avoiding customer frustration. I suggested that before:

<https://github.com/RadeonOpenCompute/ROCm/issues/844>

**Comment by JMadgwick** [comment]
>maintain support for older products as much as possible with minimum effort. I can respect that, because AMD's Radeon Technology Group needs to focus it's limited resources on the areas that matter most. However, documenting the support or even functional hardware status would be an honest step in the direction of avoiding customer frustration

I mentioned the problem with the CPU support documentation about a year ago and changes were made to improve it. However, I have noticed that the developers have been much **less active than they used to be**. Presumably they have been very busy working on gfx908 and other datacentre related Vega. I think you are right that the older hardware is forgotten.
Considering that gfx7 was originally launched with the R9 290 in 2013, it's fair enough that support has ended now. The readme should really reflect reality, it's not helping anyone by stating there is support when there is not.

Some people like to compare Nvidia CUDA to Rocm, I don't think that's fair. CUDA has been going for years, whereas gfx7 was a few years old before Rocm even got going. I also read somewhere that until recently Nvidia spent more on R&D than AMD had in revenue...

As has been mentioned, support for gfx803 seems to be on the way out. This arch is also older (first gfx8 was 2015). The problem here is that AMD was rebranding it for years and it is still possible to buy these GPUs new today (RX 580/590). Whereas the last gfx7 sold was the R9 390 around 2016.

Someone could try to improve the Readme themselves and make a pull request, but the signs of it being merged are not so good. [This one is pending since January.](https://github.com/RadeonOpenCompute/ROCm/pull/661)

**Comment by vulturm** [comment]
https://github.com/RadeonOpenCompute/ROCm/blob/master/version_history.md

_See the API reference for more details. 2.0 is the last release of active support for gfx803 architectures. In future releases, MIOpen will not actively debug and develop new features specifically for gfx803._

**Comment by Lucretia** [comment]
I would like to get this fixed as I'm on this hw and fx-8350 and cannot upgrade yet.

**Comment by JMadgwick** [comment]
I see you have commented in a few places. I still have my Hawaii GPU and it still does not work. From what I can tell nothing is being done about it. AMD seem to be concentrating on newer GPUs.
Want did you want to use ROCm for on your Hawaii GPU? None of the ported programs such as Tensorflow were ever supported on Hawaii due to no support in the MIOpen libary etc. that wouldn't change if the existing bugs were fixed.

If you want to use OpenCL then install AMDGPU-PRO and use `--opencl=legacy --headless` in the install script to install only the closed source compute driver and not any of the graphics stack. The `--headless` option is very misleading as it doesn't mean that at all and the opensource drivers (mesa etc.) continue to work fine with the Pro compute driver. I have tested the latest AMDGPU-Pro myself and it is fully working on Hawaii.

**Comment by Lucretia** [comment]
Yeah, I'm aware of the amdgpu-pro. I wanted to test out rocm. I'm got a course on ML and AI and I can't do them with the HW I have unless I can get this to work.

Is MIOpen not as open as it sounds?

**Comment by Moading** [comment]
The real scandal is the loss of features when people want to use an up to date operation systems with not so old hardware. For example, Hawaii GPUs supported OpenCL 2.0 when using the fglrx driver. When that driver was abandoned, there was no replacement that offered OpenCL 2.0. How am I supposed to develop GPGPU programs? Learn CUDA?

The scandal continues: Newer GPUs like the Radeon Pro Duo (gfx803) are advertised as OpenCL 2.0 ready. It turns out that this is true for Windows only.

**Comment by JMadgwick** [comment]
> Is MIOpen not as open as it sounds?

Well I know that **MIOpen doesn't and never did support Hawaii**. Back when Rocm was working on Hawaii (version 1.9) I tried using Tensorflow and it doesn't work (gave an error about unsupported arch). TensorFlow relies of various optimised code etc. and no code was written for Hawaii, only gfx803 and newer works with Rocm Tensorflow.
I can't find the issue where I originally asked about this because the old Tensorflow repo has since been deleted.

> Hawaii GPUs supported OpenCL 2.0 when using the fglrx driver

With the AMDGPU-PRO driver they support 1.2 with an OpenCL C version of 2.0 (presumably the driver/compiler support level).
> How am I supposed to develop GPGPU programs? Learn CUDA?

It seems that AMD want you to learn HIP. Remember that the OpenCL 2.0 spec was released around the time of Hawaii and the newer revisions are supported by nothing but Intel. OpenCL 2.0 is pretty much dead and the newer versions never lived (DOA).

**Comment by Lucretia** [comment]
> > Is MIOpen not as open as it sounds?
> 
> Well I know that **MIOpen doesn't and never did support Hawaii**. Back when Rocm was working on Hawaii ([version 1.9](http://repo.radeon.com/rocm/archive/)) I tried using Tensorflow and it doesn't work (gave an error about unsupported arch). TensorFlow relies on various optimised code etc. and no code was written for Hawaii, only gfx803 and newer works with Rocm Tensorflow.

Doesn't mean that code cannot be written. 

> > How am I supposed to develop GPGPU programs? Learn CUDA?
> 
> It seems that AMD want you to learn HIP. Remember that the OpenCL 2.0 spec was released around the time of Hawaii and the newer revisions are supported by nothing but Intel. OpenCL 2.0 is pretty much dead and the newer versions never lived (DOA).

Yes, but the hw is in development for years before so they know about OpenCL 2.0 long before and designed the hw to support it.

What's really infuriating is they refuse to get things working and they work at an ever increasingly glacial speed, along with these other smaller closed bits, i.e where it's currently crashing. If these bits were open, this would be fixed by now.

**Comment by briansp2020** [comment]
@Lucretia 
>  
>  I'm got a course on ML and AI and I can't do them with the HW I have unless I can get this to work.

If you are just getting started with ML, NVidia has much better support and you should use it to minimize any issues with the environment. If you don't have the hardware, try using Google's colaboratory (https://colab.research.google.com/notebooks/welcome.ipynb). They offer free GPU instances (with some restrictions) that should be good enough for learning ML.

**Comment by Lucretia** [comment]
> @Lucretia
> 
> > I'm got a course on ML and AI and I can't do them with the HW I have unless I can get this to work.
> 
> If you are just getting started with ML, NVidia has much better support and you should use it to minimize any issues with the environment. If you don't have the hardware, try using Google's colaboratory (https://colab.research.google.com/notebooks/welcome.ipynb). They offer free GPU instances (with some restrictions) that should be good enough for learning ML.

Ahh, thanks.

Still would like to get this working on AMD as well though, just saying.

**Comment by illwieckz** [comment]
For people looking for working OpenCL support on Hawaii/Grenada gfx701 on Ubuntu 19.10 without a need any ROCm specific feature, I wrote there a tutorial to install the legacy OpenCL driver from amdgpu-pro package:
https://github.com/RadeonOpenCompute/ROCm/issues/484#issuecomment-554738964

This seems to be the only way to do GPU computation on Hawaii today.

**Comment by walterav1984** [comment]
Thanks @illwieckz for keeping us informed, I only found [this](https://www.youtube.com/watch?v=97fj4bGJxVM) youtube video for using AMDGPU-PRO ubuntu 19.04 which states that its procedure didn't work with 19.10 but I would like to try yours on 19.10. 

For what its worth, eventhough AMDGPU-PRO drivers focus on stable releases like ubuntu 18.04 it works with its LTS hardware updated kernel/graphics stack from 18.04.3 only by forcing kernel AMDGPU instead of RADEON during boot, followed with default AMDGPU-PRO install instructions . 

Therefor I was able to use the AMDGPU-pro driver on ubuntu 18.04.3 with Davinci Resolve 16 even from a live session by only forcing the default kernel AMDGPU drivers from grub/isolinux bootloader `radeon.cik_support=0 radeon.si_support=0 amdgpu.cik_support=1 amdgpu.si_support=1 amdgpu.dc=1`  and adding the legacy OPENCL component!

**Comment by walterav1984** [comment]
I can indeed confirm that @illwieckz his ubuntu 19.10 amdgpu-pro opencl legacy trick worked (tested with Davinci Resolve 16), however it only worked for opencl and not the pro "opengl and vulkan" modules since it will force dkms on a unsupported linux 5.3 kernel and break the packet manager.

**Comment by illwieckz** [comment]
@walterav1984 thanks for confirmation!

I don't have a need for proprietary opengl/vulkan stack to work so I never spent time to attempt anything on it. I guess the only need for proprietary opengl would be the opengl compatibility profiles (I know there is now work on them on mesa side but I don't know how much complete it is yet). Otherwise, I think even AMD recommends mesa for OpenGL.

**Comment by ROCmSupport** [comment]
Hi All,
Hawaii is no more officially ROCm supported device. Please check for more details:
[https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support](url)
Thank you.

**Comment by TByte007** [comment]
ust a quick question. Are you insane ? Currently the ONLY affordable GPUs are GFX7 and GFX8 ... and GFX8 is NOT REALLY. I'm not buying another AMD card ever. How come nVidia is able to support their older cards and you cant ?!?

**Comment by Bengt** [comment]
@TByte007

-   Your tone is very out of place here. This is a public forum where you are talking to/amongst professionals. Please reconsider.
-   Yes, Nvidia does have more broad compute support. They but also have like 10 times the financial and personnel power. So, give AMD a break, please. I think asking to support a feature in GPUs that were most recently released over a year prior to said feature is quite a stretch.
-   Nobody is judging you for buying Nvidia, please go ahead and buy the better product. We will keep improving this one in the meantime.

**Comment by TByte007** [comment]
> @TByte007
> 
> * Your tone is very out of place here. This is a public forum where you are talking to/amongst professionals. Please reconsider.
> * Yes, Nvidia does have more broad compute support. They but also have like 10 times the financial and personnel power. So, give AMD a break, please. I think asking to support a feature in GPUs that were most recently released over a year prior to said feature is quite a stretch.
> * Nobody is judging you for buying Nvidia, please go ahead and buy the better product. We will keep improving this one in the meantime.

No I will not and I'm saying what EVERYBODY is thinking. And I don't think u need a ton of money to support a single driver. And heaving in mind that they are pretty find on the money side given the prices of ... everything currently it is a deserved criticism. Oh and I have like 6-7 GPU7/8 cards that are useless now. So "buying nVidia" at the current prices is not really a solution.

**Comment by illwieckz** [comment]
Tone apart, yes OpenCL is the shame of AMD. Now AMD GPUs are so good on kernel and distribution integration, Nvidia is decade late on that topic. Now AMD GPUs are so good on graphical side that Nvidia can't keep up anymore: as a game developer, I can testimony we face weird kind of bugs we never seen on AMD, like [this](https://github.com/DaemonEngine/Daemon/issues/368), [this](https://github.com/DaemonEngine/Daemon/issues/472) or [this](https://github.com/DaemonEngine/Daemon/issues/474)…

But on compute side… AMD status is still worst than what Nvidia was doing 10 years ago. This is super weird. AMD is close to take the market by storm, but just forgot to care enough about people wanting to _work_ with their great piece of hardware, and not only _game_ with.

It looks like the only hope for us, consumers, is to wait for Mesa OpenCL (`clover`/`libclc-amdgcn`) to reach completeness. But for some unknown reasons, it looks like the actual developers working on OpenCL on Mesa are more focusing on Nvidia GPUs (with nouveau) than AMD… I don't know if someone is funding that nouveau effort in order to get Nvidia GPUs working with free open source compute stack before AMD, but well, it's a shame.

The Mesa OpenCL is already twice faster than any variant of AMD-APP I was able to test on some workflow like Luxmark, but support is still incomplete so softwares like Darktable can't make use of it. I know ROCm has more than OpenCL, but for OpenCL we just need that Mesa OpenCL reaching completeness.

If any AMD official walks around, and hear us, listen, compute is the only remaining rational motivation to by Nvidia GPUs today. As users we just need OpenCL being implemented for at least all GCN/RDNA GPUs, and then, every free software enthusiast will just be able to encourage everyone to never buy Nvidia again and praise AMD instead.

By implementing OpenCL on _all_ GCN and RDNA GPUs and by doing good communication around that, Nvidia can lose the Linux market. Nvidia already lost the living-room console market, Nvidia can lose the workstation market starting from the Linux side and building that momentum, because then, PC vendors would have no risk to integrate AMD GPUs in their product, instead of putting Nvidia everywhere « just in case » there are linux compute users among their customers.

**Comment by illwieckz** [comment]
This issue has to be reopened. The Hawaii architecture is still listed in README today (2021-11-22):

> - GFX7 GPUs
>   - "Hawaii" chips, such as the AMD Radeon R9 390X and FirePro W9100

> Experimental support for our Hawaii (GFX7) GPUs (Radeon R9 290, R9 390, FirePro W9100, S9150, S9170) does not require or take advantage of PCIe Atomics. However, we still recommend that you use a CPU from the list provided above for compatibility purposes.

**Comment by ROCmSupport** [comment]
Hi @illwieckz 
Looks like Readme needs some modifications. Actually gfx7 support was dropped long back.
Let me work with Documentation team on this. Thank you.
