### ISSUE TITLE
Linux container on ROCm

### ISSUE THREAD

**Issue by smithakihide** [RadeonOpenCompute/ROCm#886]
Hello, thank you to read this issue.

How can I use ROCm in a Linux container, called [LXC](https://linuxcontainers.org/)?
If you know any about this topic, please tell me.

**Comment by Bengt** [comment]
There are docker images for ROCm Tensorflow upstream. Do these work for you?

**Comment by smithakihide** [comment]
Thank you for replying.
I have not tried Docker image of ROCm Tensorflow yet because it is not in my interest.
I would like to use ROCm in my original program with C++. Using Tensorflow is not my purpose. So although there might be docker images other than for Tensorflow, even in the case, I would like to use LXC for system container, not Docker.

**Comment by sunway513** [comment]
Hi @smithakihide , does the following rocm dev docker work for you:
https://hub.docker.com/r/rocm/dev-ubuntu-18.04

**Comment by extraymond** [comment]
> Hello, thank you to read this issue.
> 
> How can I use ROCm in a Linux container, called [LXC](https://linuxcontainers.org/)?
> If you know any about this topic, please tell me.

Hi! I've tried setting up rocm in a lxd container.
Here's the needed setup if anyone is interested.

After setting up rocm the way would've done on the host, assumed the following:
1. you are in the video group
2. you've allow /dev/kfd to be access by video group.

We can now use lxd's config device option to expose the host's devices with the correct permission so that the guest container can access it as a non-root user.

```bash
lxc config device add $container_name $kfd_device_name_you_want unix-char gid=${gid_of_group_video} source=/dev/kfd mode=666
lxc config device add $container_name $gpu_name gid=${gid_of_group_video}
```

So for example my config would have these two devices:
```yaml
devices:
  gpu:
    gid: "44"
    type: gpu
  kfd:
    gid: "44"
    mode: "666"
    source: /dev/kfd
    type: unix-char

```

![Screenshot from 2020-02-20 20-51-56](https://user-images.githubusercontent.com/707176/74935375-17e9ac80-5423-11ea-8944-6bffacff2d2a.png)

![Screenshot from 2020-02-20 20-53-27](https://user-images.githubusercontent.com/707176/74935380-1ae49d00-5423-11ea-8f0a-0c2ca12af868.png)

**Comment by smithakihide** [comment]
really? thank you very much to tell me your trial!.

I' ll try it too.

**Comment by DocMAX** [comment]
I can't make kfd work in lcx container...
```
root@ollama:~# rocminfo
ROCk module is loaded
Unable to open /dev/kfd read-write: Operation not permitted
root is member of render group

```
